import { EnemyType } from '../types/types'

export function getRandomEnemyId(minPower?: number, maxPower?: number) {
	if (!minPower && !maxPower) {
		return Math.floor(Math.random() * enemies.length)
	}
	const enemiesInRange = enemies.filter(
		enemy => enemy.power > (minPower ?? 0) && enemy.power < (maxPower ?? 1000)
	)
	return enemiesInRange[Math.floor(Math.random() * enemiesInRange.length)].id
}

const enemies: EnemyType[] = [
	{
		id: 0,
		name: 'Древний скелет',
		range: 'melee',
		maxHp: 10,
		img: 'src/assets/ArchSkeleton.png',
		damage: 10,
		hp: 10,
		power: 3,
	},
	{
		id: 1,
		name: 'Древний мертвец',
		range: 'melee',
		maxHp: 6,
		img: 'src/assets/DeadMan.png',
		damage: 5,
		hp: 6,
		power: 1,
	},
	{
		id: 2,
		name: 'Древний тролль',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/Troll.png',
		damage: 30,
		hp: 30,
		power: 10,
	},
	{
		id: 3,
		name: 'Древний элементаль',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elemental.png',
		damage: 30,
		hp: 10,
		power: 8,
	},
	{
		id: 4,
		name: 'Древний хаос',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Chaos.png',
		damage: 55,
		hp: 55,
		power: 20,
	},
	{
		id: 5,
		name: 'Древний эльф',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elf.png',
		damage: 30,
		hp: 15,
		power: 9,
	},
	{
		id: 6,
		name: 'Древний голем',
		range: 'melee',
		maxHp: 65,
		img: 'src/assets/Golem.png',
		damage: 35,
		hp: 65,
		power: 16,
	},
	{
		id: 7,
		name: 'Древний призрак',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Ghost.png',
		damage: 10,
		hp: 105,
		power: 20,
	},
	{
		id: 8,
		name: 'Древний маг',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Mage.png',
		damage: 40,
		hp: 15,
		power: 10,
	},
	{
		id: 9,
		name: 'Древний варвар',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/barbarian.png',
		damage: 30,
		hp: 55,
		power: 14,
	},
	{
		id: 10,
		name: 'Древний великан',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/IceGiant.png',
		damage: 35,
		hp: 105,
		power: 23,
	},
	{
		id: 11,
		name: 'Древний дракон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/FlameDrago.png',
		damage: 45,
		hp: 105,
		power: 26,
	},
	{
		id: 12,
		name: 'Древний ящер',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Lizzard.png',
		damage: 55,
		hp: 10,
		power: 12,
	},
	{
		id: 13,
		name: 'Древний король',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/king.png',
		damage: 30,
		hp: 30,
		power: 10,
	},
	{
		id: 14,
		name: 'Древний демон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Devil.png',
		damage: 55,
		hp: 105,
		power: 28,
	},
	{
		id: 15,
		name: 'Древний зверь',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/Beast.png',
		damage: 30,
		hp: 55,
		power: 14,
	},
	{
		id: 16,
		name: 'Древний лучник',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Archer.png',
		damage: 20,
		hp: 10,
		power: 6,
	},
	{
		id: 17,
		name: 'Древний рыцарь',
		range: 'melee',
		maxHp: 80,
		img: 'src/assets/DarkKnight.png',
		damage: 50,
		hp: 80,
		power: 21,
	},
	{
		id: 18,
		name: 'Злобный скелет',
		range: 'melee',
		maxHp: 10,
		img: 'src/assets/ArchSkeleton.png',
		damage: 15,
		hp: 10,
		power: 4,
	},
	{
		id: 19,
		name: 'Злобный мертвец',
		range: 'melee',
		maxHp: 6,
		img: 'src/assets/DeadMan.png',
		damage: 10,
		hp: 6,
		power: 2,
	},
	{
		id: 20,
		name: 'Злобный тролль',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/Troll.png',
		damage: 35,
		hp: 30,
		power: 10,
	},
	{
		id: 21,
		name: 'Злобный элементаль',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elemental.png',
		damage: 35,
		hp: 10,
		power: 9,
	},
	{
		id: 22,
		name: 'Злобный хаос',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Chaos.png',
		damage: 60,
		hp: 55,
		power: 20,
	},
	{
		id: 23,
		name: 'Злобный эльф',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elf.png',
		damage: 35,
		hp: 15,
		power: 10,
	},
	{
		id: 24,
		name: 'Злобный голем',
		range: 'melee',
		maxHp: 65,
		img: 'src/assets/Golem.png',
		damage: 40,
		hp: 65,
		power: 17,
	},
	{
		id: 25,
		name: 'Злобный призрак',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Ghost.png',
		damage: 15,
		hp: 105,
		power: 21,
	},
	{
		id: 26,
		name: 'Злобный маг',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Mage.png',
		damage: 45,
		hp: 15,
		power: 11,
	},
	{
		id: 27,
		name: 'Злобный варвар',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/barbarian.png',
		damage: 35,
		hp: 55,
		power: 15,
	},
	{
		id: 28,
		name: 'Злобный великан',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/IceGiant.png',
		damage: 40,
		hp: 105,
		power: 24,
	},
	{
		id: 29,
		name: 'Злобный дракон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/FlameDrago.png',
		damage: 50,
		hp: 105,
		power: 27,
	},
	{
		id: 30,
		name: 'Злобный ящер',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Lizzard.png',
		damage: 60,
		hp: 10,
		power: 13,
	},
	{
		id: 31,
		name: 'Злобный король',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/king.png',
		damage: 35,
		hp: 30,
		power: 10,
	},
	{
		id: 32,
		name: 'Злобный демон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Devil.png',
		damage: 60,
		hp: 105,
		power: 29,
	},
	{
		id: 33,
		name: 'Злобный зверь',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/Beast.png',
		damage: 35,
		hp: 55,
		power: 15,
	},
	{
		id: 34,
		name: 'Злобный лучник',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Archer.png',
		damage: 25,
		hp: 10,
		power: 7,
	},
	{
		id: 35,
		name: 'Злобный рыцарь',
		range: 'melee',
		maxHp: 80,
		img: 'src/assets/DarkKnight.png',
		damage: 55,
		hp: 80,
		power: 22,
	},
	{
		id: 36,
		name: 'Огненный скелет',
		range: 'melee',
		maxHp: 10,
		img: 'src/assets/ArchSkeleton.png',
		damage: 15,
		hp: 10,
		power: 4,
	},
	{
		id: 37,
		name: 'Огненный мертвец',
		range: 'melee',
		maxHp: 6,
		img: 'src/assets/DeadMan.png',
		damage: 10,
		hp: 6,
		power: 2,
	},
	{
		id: 38,
		name: 'Огненный тролль',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/Troll.png',
		damage: 35,
		hp: 30,
		power: 10,
	},
	{
		id: 39,
		name: 'Огненный элементаль',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elemental.png',
		damage: 35,
		hp: 10,
		power: 9,
	},
	{
		id: 40,
		name: 'Огненный хаос',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Chaos.png',
		damage: 60,
		hp: 55,
		power: 20,
	},
	{
		id: 41,
		name: 'Огненный эльф',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elf.png',
		damage: 35,
		hp: 15,
		power: 10,
	},
	{
		id: 42,
		name: 'Огненный голем',
		range: 'melee',
		maxHp: 65,
		img: 'src/assets/Golem.png',
		damage: 40,
		hp: 65,
		power: 17,
	},
	{
		id: 43,
		name: 'Огненный призрак',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Ghost.png',
		damage: 15,
		hp: 105,
		power: 21,
	},
	{
		id: 44,
		name: 'Огненный маг',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Mage.png',
		damage: 45,
		hp: 15,
		power: 11,
	},
	{
		id: 45,
		name: 'Огненный варвар',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/barbarian.png',
		damage: 35,
		hp: 55,
		power: 15,
	},
	{
		id: 46,
		name: 'Огненный великан',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/IceGiant.png',
		damage: 40,
		hp: 105,
		power: 24,
	},
	{
		id: 47,
		name: 'Огненный дракон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/FlameDrago.png',
		damage: 50,
		hp: 105,
		power: 27,
	},
	{
		id: 48,
		name: 'Огненный ящер',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Lizzard.png',
		damage: 60,
		hp: 10,
		power: 13,
	},
	{
		id: 49,
		name: 'Огненный король',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/king.png',
		damage: 35,
		hp: 30,
		power: 10,
	},
	{
		id: 50,
		name: 'Огненный демон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Devil.png',
		damage: 60,
		hp: 105,
		power: 29,
	},
	{
		id: 51,
		name: 'Огненный зверь',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/Beast.png',
		damage: 35,
		hp: 55,
		power: 15,
	},
	{
		id: 52,
		name: 'Огненный лучник',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Archer.png',
		damage: 25,
		hp: 10,
		power: 7,
	},
	{
		id: 53,
		name: 'Огненный рыцарь',
		range: 'melee',
		maxHp: 80,
		img: 'src/assets/DarkKnight.png',
		damage: 55,
		hp: 80,
		power: 22,
	},
	{
		id: 54,
		name: 'Песчаный скелет',
		range: 'melee',
		maxHp: 15,
		img: 'src/assets/ArchSkeleton.png',
		damage: 10,
		hp: 15,
		power: 4,
	},
	{
		id: 55,
		name: 'Песчаный мертвец',
		range: 'melee',
		maxHp: 11,
		img: 'src/assets/DeadMan.png',
		damage: 5,
		hp: 11,
		power: 2,
	},
	{
		id: 56,
		name: 'Песчаный тролль',
		range: 'melee',
		maxHp: 35,
		img: 'src/assets/Troll.png',
		damage: 30,
		hp: 35,
		power: 10,
	},
	{
		id: 57,
		name: 'Песчаный элементаль',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elemental.png',
		damage: 30,
		hp: 15,
		power: 9,
	},
	{
		id: 58,
		name: 'Песчаный хаос',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Chaos.png',
		damage: 55,
		hp: 60,
		power: 20,
	},
	{
		id: 59,
		name: 'Песчаный эльф',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Elf.png',
		damage: 30,
		hp: 20,
		power: 10,
	},
	{
		id: 60,
		name: 'Песчаный голем',
		range: 'melee',
		maxHp: 70,
		img: 'src/assets/Golem.png',
		damage: 35,
		hp: 70,
		power: 17,
	},
	{
		id: 61,
		name: 'Песчаный призрак',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Ghost.png',
		damage: 10,
		hp: 110,
		power: 21,
	},
	{
		id: 62,
		name: 'Песчаный маг',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Mage.png',
		damage: 40,
		hp: 20,
		power: 11,
	},
	{
		id: 63,
		name: 'Песчаный варвар',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/barbarian.png',
		damage: 30,
		hp: 60,
		power: 15,
	},
	{
		id: 64,
		name: 'Песчаный великан',
		range: 'melee',
		maxHp: 110,
		img: 'src/assets/IceGiant.png',
		damage: 35,
		hp: 110,
		power: 24,
	},
	{
		id: 65,
		name: 'Песчаный дракон',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/FlameDrago.png',
		damage: 45,
		hp: 110,
		power: 27,
	},
	{
		id: 66,
		name: 'Песчаный ящер',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Lizzard.png',
		damage: 55,
		hp: 15,
		power: 13,
	},
	{
		id: 67,
		name: 'Песчаный король',
		range: 'melee',
		maxHp: 35,
		img: 'src/assets/king.png',
		damage: 30,
		hp: 35,
		power: 10,
	},
	{
		id: 68,
		name: 'Песчаный демон',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Devil.png',
		damage: 55,
		hp: 110,
		power: 29,
	},
	{
		id: 69,
		name: 'Песчаный зверь',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/Beast.png',
		damage: 30,
		hp: 60,
		power: 15,
	},
	{
		id: 70,
		name: 'Песчаный лучник',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Archer.png',
		damage: 20,
		hp: 15,
		power: 7,
	},
	{
		id: 71,
		name: 'Песчаный рыцарь',
		range: 'melee',
		maxHp: 85,
		img: 'src/assets/DarkKnight.png',
		damage: 50,
		hp: 85,
		power: 22,
	},
	{
		id: 72,
		name: 'Каменный скелет',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/ArchSkeleton.png',
		damage: 10,
		hp: 55,
		power: 10,
	},
	{
		id: 73,
		name: 'Каменный мертвец',
		range: 'melee',
		maxHp: 51,
		img: 'src/assets/DeadMan.png',
		damage: 5,
		hp: 51,
		power: 9,
	},
	{
		id: 74,
		name: 'Каменный тролль',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/Troll.png',
		damage: 30,
		hp: 75,
		power: 17,
	},
	{
		id: 75,
		name: 'Каменный элементаль',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Elemental.png',
		damage: 30,
		hp: 55,
		power: 15,
	},
	{
		id: 76,
		name: 'Каменный хаос',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Chaos.png',
		damage: 55,
		hp: 100,
		power: 27,
	},
	{
		id: 77,
		name: 'Каменный эльф',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Elf.png',
		damage: 30,
		hp: 60,
		power: 16,
	},
	{
		id: 78,
		name: 'Каменный голем',
		range: 'melee',
		maxHp: 110,
		img: 'src/assets/Golem.png',
		damage: 35,
		hp: 110,
		power: 24,
	},
	{
		id: 79,
		name: 'Каменный призрак',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Ghost.png',
		damage: 10,
		hp: 150,
		power: 28,
	},
	{
		id: 80,
		name: 'Каменный маг',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Mage.png',
		damage: 40,
		hp: 60,
		power: 18,
	},
	{
		id: 81,
		name: 'Каменный варвар',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/barbarian.png',
		damage: 30,
		hp: 100,
		power: 21,
	},
	{
		id: 82,
		name: 'Каменный великан',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/IceGiant.png',
		damage: 35,
		hp: 150,
		power: 30,
	},
	{
		id: 83,
		name: 'Каменный дракон',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/FlameDrago.png',
		damage: 45,
		hp: 150,
		power: 34,
	},
	{
		id: 84,
		name: 'Каменный ящер',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Lizzard.png',
		damage: 55,
		hp: 55,
		power: 20,
	},
	{
		id: 85,
		name: 'Каменный король',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/king.png',
		damage: 30,
		hp: 75,
		power: 17,
	},
	{
		id: 86,
		name: 'Каменный демон',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Devil.png',
		damage: 55,
		hp: 150,
		power: 35,
	},
	{
		id: 87,
		name: 'Каменный зверь',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/Beast.png',
		damage: 30,
		hp: 100,
		power: 21,
	},
	{
		id: 88,
		name: 'Каменный лучник',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Archer.png',
		damage: 20,
		hp: 55,
		power: 14,
	},
	{
		id: 89,
		name: 'Каменный рыцарь',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/DarkKnight.png',
		damage: 50,
		hp: 125,
		power: 29,
	},
	{
		id: 90,
		name: 'Пылающий скелет',
		range: 'melee',
		maxHp: 10,
		img: 'src/assets/ArchSkeleton.png',
		damage: 25,
		hp: 10,
		power: 5,
	},
	{
		id: 91,
		name: 'Пылающий мертвец',
		range: 'melee',
		maxHp: 6,
		img: 'src/assets/DeadMan.png',
		damage: 20,
		hp: 6,
		power: 4,
	},
	{
		id: 92,
		name: 'Пылающий тролль',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/Troll.png',
		damage: 45,
		hp: 30,
		power: 12,
	},
	{
		id: 93,
		name: 'Пылающий элементаль',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elemental.png',
		damage: 45,
		hp: 10,
		power: 10,
	},
	{
		id: 94,
		name: 'Пылающий хаос',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Chaos.png',
		damage: 70,
		hp: 55,
		power: 22,
	},
	{
		id: 95,
		name: 'Пылающий эльф',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elf.png',
		damage: 45,
		hp: 15,
		power: 11,
	},
	{
		id: 96,
		name: 'Пылающий голем',
		range: 'melee',
		maxHp: 65,
		img: 'src/assets/Golem.png',
		damage: 50,
		hp: 65,
		power: 19,
	},
	{
		id: 97,
		name: 'Пылающий призрак',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Ghost.png',
		damage: 25,
		hp: 105,
		power: 23,
	},
	{
		id: 98,
		name: 'Пылающий маг',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Mage.png',
		damage: 55,
		hp: 15,
		power: 13,
	},
	{
		id: 99,
		name: 'Пылающий варвар',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/barbarian.png',
		damage: 45,
		hp: 55,
		power: 16,
	},
	{
		id: 100,
		name: 'Пылающий великан',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/IceGiant.png',
		damage: 50,
		hp: 105,
		power: 25,
	},
	{
		id: 101,
		name: 'Пылающий дракон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/FlameDrago.png',
		damage: 60,
		hp: 105,
		power: 29,
	},
	{
		id: 102,
		name: 'Пылающий ящер',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Lizzard.png',
		damage: 70,
		hp: 10,
		power: 15,
	},
	{
		id: 103,
		name: 'Пылающий король',
		range: 'melee',
		maxHp: 30,
		img: 'src/assets/king.png',
		damage: 45,
		hp: 30,
		power: 12,
	},
	{
		id: 104,
		name: 'Пылающий демон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Devil.png',
		damage: 70,
		hp: 105,
		power: 30,
	},
	{
		id: 105,
		name: 'Пылающий зверь',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/Beast.png',
		damage: 45,
		hp: 55,
		power: 16,
	},
	{
		id: 106,
		name: 'Пылающий лучник',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Archer.png',
		damage: 35,
		hp: 10,
		power: 9,
	},
	{
		id: 107,
		name: 'Пылающий рыцарь',
		range: 'melee',
		maxHp: 80,
		img: 'src/assets/DarkKnight.png',
		damage: 65,
		hp: 80,
		power: 24,
	},
	{
		id: 108,
		name: 'Лесной скелет',
		range: 'melee',
		maxHp: 15,
		img: 'src/assets/ArchSkeleton.png',
		damage: 15,
		hp: 15,
		power: 5,
	},
	{
		id: 109,
		name: 'Лесной мертвец',
		range: 'melee',
		maxHp: 11,
		img: 'src/assets/DeadMan.png',
		damage: 10,
		hp: 11,
		power: 3,
	},
	{
		id: 110,
		name: 'Лесной тролль',
		range: 'melee',
		maxHp: 35,
		img: 'src/assets/Troll.png',
		damage: 35,
		hp: 35,
		power: 11,
	},
	{
		id: 111,
		name: 'Лесной элементаль',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elemental.png',
		damage: 35,
		hp: 15,
		power: 10,
	},
	{
		id: 112,
		name: 'Лесной хаос',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Chaos.png',
		damage: 60,
		hp: 60,
		power: 21,
	},
	{
		id: 113,
		name: 'Лесной эльф',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Elf.png',
		damage: 35,
		hp: 20,
		power: 10,
	},
	{
		id: 114,
		name: 'Лесной голем',
		range: 'melee',
		maxHp: 70,
		img: 'src/assets/Golem.png',
		damage: 40,
		hp: 70,
		power: 18,
	},
	{
		id: 115,
		name: 'Лесной призрак',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Ghost.png',
		damage: 15,
		hp: 110,
		power: 22,
	},
	{
		id: 116,
		name: 'Лесной маг',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Mage.png',
		damage: 45,
		hp: 20,
		power: 12,
	},
	{
		id: 117,
		name: 'Лесной варвар',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/barbarian.png',
		damage: 35,
		hp: 60,
		power: 15,
	},
	{
		id: 118,
		name: 'Лесной великан',
		range: 'melee',
		maxHp: 110,
		img: 'src/assets/IceGiant.png',
		damage: 40,
		hp: 110,
		power: 25,
	},
	{
		id: 119,
		name: 'Лесной дракон',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/FlameDrago.png',
		damage: 50,
		hp: 110,
		power: 28,
	},
	{
		id: 120,
		name: 'Лесной ящер',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Lizzard.png',
		damage: 60,
		hp: 15,
		power: 14,
	},
	{
		id: 121,
		name: 'Лесной король',
		range: 'melee',
		maxHp: 35,
		img: 'src/assets/king.png',
		damage: 35,
		hp: 35,
		power: 11,
	},
	{
		id: 122,
		name: 'Лесной демон',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Devil.png',
		damage: 60,
		hp: 110,
		power: 30,
	},
	{
		id: 123,
		name: 'Лесной зверь',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/Beast.png',
		damage: 35,
		hp: 60,
		power: 15,
	},
	{
		id: 124,
		name: 'Лесной лучник',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Archer.png',
		damage: 25,
		hp: 15,
		power: 8,
	},
	{
		id: 125,
		name: 'Лесной рыцарь',
		range: 'melee',
		maxHp: 85,
		img: 'src/assets/DarkKnight.png',
		damage: 55,
		hp: 85,
		power: 23,
	},
	{
		id: 126,
		name: 'Мёртвый скелет',
		range: 'melee',
		maxHp: 5,
		img: 'src/assets/ArchSkeleton.png',
		damage: 25,
		hp: 5,
		power: 5,
	},
	{
		id: 127,
		name: 'Мёртвый мертвец',
		range: 'melee',
		maxHp: 1,
		img: 'src/assets/DeadMan.png',
		damage: 20,
		hp: 1,
		power: 3,
	},
	{
		id: 128,
		name: 'Мёртвый тролль',
		range: 'melee',
		maxHp: 25,
		img: 'src/assets/Troll.png',
		damage: 45,
		hp: 25,
		power: 11,
	},
	{
		id: 129,
		name: 'Мёртвый элементаль',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Elemental.png',
		damage: 45,
		hp: 5,
		power: 10,
	},
	{
		id: 130,
		name: 'Мёртвый хаос',
		range: 'ranged',
		maxHp: 50,
		img: 'src/assets/Chaos.png',
		damage: 70,
		hp: 50,
		power: 21,
	},
	{
		id: 131,
		name: 'Мёртвый эльф',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elf.png',
		damage: 45,
		hp: 10,
		power: 10,
	},
	{
		id: 132,
		name: 'Мёртвый голем',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/Golem.png',
		damage: 50,
		hp: 60,
		power: 18,
	},
	{
		id: 133,
		name: 'Мёртвый призрак',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Ghost.png',
		damage: 25,
		hp: 100,
		power: 22,
	},
	{
		id: 134,
		name: 'Мёртвый маг',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Mage.png',
		damage: 55,
		hp: 10,
		power: 12,
	},
	{
		id: 135,
		name: 'Мёртвый варвар',
		range: 'melee',
		maxHp: 50,
		img: 'src/assets/barbarian.png',
		damage: 45,
		hp: 50,
		power: 15,
	},
	{
		id: 136,
		name: 'Мёртвый великан',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/IceGiant.png',
		damage: 50,
		hp: 100,
		power: 25,
	},
	{
		id: 137,
		name: 'Мёртвый дракон',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/FlameDrago.png',
		damage: 60,
		hp: 100,
		power: 28,
	},
	{
		id: 138,
		name: 'Мёртвый ящер',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Lizzard.png',
		damage: 70,
		hp: 5,
		power: 14,
	},
	{
		id: 139,
		name: 'Мёртвый король',
		range: 'melee',
		maxHp: 25,
		img: 'src/assets/king.png',
		damage: 45,
		hp: 25,
		power: 11,
	},
	{
		id: 140,
		name: 'Мёртвый демон',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Devil.png',
		damage: 70,
		hp: 100,
		power: 30,
	},
	{
		id: 141,
		name: 'Мёртвый зверь',
		range: 'melee',
		maxHp: 50,
		img: 'src/assets/Beast.png',
		damage: 45,
		hp: 50,
		power: 15,
	},
	{
		id: 142,
		name: 'Мёртвый лучник',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Archer.png',
		damage: 35,
		hp: 5,
		power: 8,
	},
	{
		id: 143,
		name: 'Мёртвый рыцарь',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/DarkKnight.png',
		damage: 65,
		hp: 75,
		power: 23,
	},
	{
		id: 144,
		name: 'Водный скелет',
		range: 'melee',
		maxHp: 5,
		img: 'src/assets/ArchSkeleton.png',
		damage: 20,
		hp: 5,
		power: 4,
	},
	{
		id: 145,
		name: 'Водный мертвец',
		range: 'melee',
		maxHp: 1,
		img: 'src/assets/DeadMan.png',
		damage: 15,
		hp: 1,
		power: 2,
	},
	{
		id: 146,
		name: 'Водный тролль',
		range: 'melee',
		maxHp: 25,
		img: 'src/assets/Troll.png',
		damage: 40,
		hp: 25,
		power: 10,
	},
	{
		id: 147,
		name: 'Водный элементаль',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Elemental.png',
		damage: 40,
		hp: 5,
		power: 9,
	},
	{
		id: 148,
		name: 'Водный хаос',
		range: 'ranged',
		maxHp: 50,
		img: 'src/assets/Chaos.png',
		damage: 65,
		hp: 50,
		power: 20,
	},
	{
		id: 149,
		name: 'Водный эльф',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elf.png',
		damage: 40,
		hp: 10,
		power: 10,
	},
	{
		id: 150,
		name: 'Водный голем',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/Golem.png',
		damage: 45,
		hp: 60,
		power: 17,
	},
	{
		id: 151,
		name: 'Водный призрак',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Ghost.png',
		damage: 20,
		hp: 100,
		power: 21,
	},
	{
		id: 152,
		name: 'Водный маг',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Mage.png',
		damage: 50,
		hp: 10,
		power: 11,
	},
	{
		id: 153,
		name: 'Водный варвар',
		range: 'melee',
		maxHp: 50,
		img: 'src/assets/barbarian.png',
		damage: 40,
		hp: 50,
		power: 15,
	},
	{
		id: 154,
		name: 'Водный великан',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/IceGiant.png',
		damage: 45,
		hp: 100,
		power: 24,
	},
	{
		id: 155,
		name: 'Водный дракон',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/FlameDrago.png',
		damage: 55,
		hp: 100,
		power: 27,
	},
	{
		id: 156,
		name: 'Водный ящер',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Lizzard.png',
		damage: 65,
		hp: 5,
		power: 13,
	},
	{
		id: 157,
		name: 'Водный король',
		range: 'melee',
		maxHp: 25,
		img: 'src/assets/king.png',
		damage: 40,
		hp: 25,
		power: 10,
	},
	{
		id: 158,
		name: 'Водный демон',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Devil.png',
		damage: 65,
		hp: 100,
		power: 29,
	},
	{
		id: 159,
		name: 'Водный зверь',
		range: 'melee',
		maxHp: 50,
		img: 'src/assets/Beast.png',
		damage: 40,
		hp: 50,
		power: 15,
	},
	{
		id: 160,
		name: 'Водный лучник',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Archer.png',
		damage: 30,
		hp: 5,
		power: 7,
	},
	{
		id: 161,
		name: 'Водный рыцарь',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/DarkKnight.png',
		damage: 60,
		hp: 75,
		power: 22,
	},
	{
		id: 162,
		name: 'Земной скелет',
		range: 'melee',
		maxHp: 5,
		img: 'src/assets/ArchSkeleton.png',
		damage: 10,
		hp: 5,
		power: 2,
	},
	{
		id: 163,
		name: 'Земной мертвец',
		range: 'melee',
		maxHp: 1,
		img: 'src/assets/DeadMan.png',
		damage: 5,
		hp: 1,
		power: 1,
	},
	{
		id: 164,
		name: 'Земной тролль',
		range: 'melee',
		maxHp: 25,
		img: 'src/assets/Troll.png',
		damage: 30,
		hp: 25,
		power: 9,
	},
	{
		id: 165,
		name: 'Земной элементаль',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Elemental.png',
		damage: 30,
		hp: 5,
		power: 7,
	},
	{
		id: 166,
		name: 'Земной хаос',
		range: 'ranged',
		maxHp: 50,
		img: 'src/assets/Chaos.png',
		damage: 55,
		hp: 50,
		power: 19,
	},
	{
		id: 167,
		name: 'Земной эльф',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elf.png',
		damage: 30,
		hp: 10,
		power: 8,
	},
	{
		id: 168,
		name: 'Земной голем',
		range: 'melee',
		maxHp: 60,
		img: 'src/assets/Golem.png',
		damage: 35,
		hp: 60,
		power: 15,
	},
	{
		id: 169,
		name: 'Земной призрак',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Ghost.png',
		damage: 10,
		hp: 100,
		power: 20,
	},
	{
		id: 170,
		name: 'Земной маг',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Mage.png',
		damage: 40,
		hp: 10,
		power: 10,
	},
	{
		id: 171,
		name: 'Земной варвар',
		range: 'melee',
		maxHp: 50,
		img: 'src/assets/barbarian.png',
		damage: 30,
		hp: 50,
		power: 13,
	},
	{
		id: 172,
		name: 'Земной великан',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/IceGiant.png',
		damage: 35,
		hp: 100,
		power: 22,
	},
	{
		id: 173,
		name: 'Земной дракон',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/FlameDrago.png',
		damage: 45,
		hp: 100,
		power: 25,
	},
	{
		id: 174,
		name: 'Земной ящер',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Lizzard.png',
		damage: 55,
		hp: 5,
		power: 11,
	},
	{
		id: 175,
		name: 'Земной король',
		range: 'melee',
		maxHp: 25,
		img: 'src/assets/king.png',
		damage: 30,
		hp: 25,
		power: 9,
	},
	{
		id: 176,
		name: 'Земной демон',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Devil.png',
		damage: 55,
		hp: 100,
		power: 27,
	},
	{
		id: 177,
		name: 'Земной зверь',
		range: 'melee',
		maxHp: 50,
		img: 'src/assets/Beast.png',
		damage: 30,
		hp: 50,
		power: 13,
	},
	{
		id: 178,
		name: 'Земной лучник',
		range: 'ranged',
		maxHp: 5,
		img: 'src/assets/Archer.png',
		damage: 20,
		hp: 5,
		power: 5,
	},
	{
		id: 179,
		name: 'Земной рыцарь',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/DarkKnight.png',
		damage: 50,
		hp: 75,
		power: 20,
	},
	{
		id: 180,
		name: 'Темный скелет',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/ArchSkeleton.png',
		damage: 35,
		hp: 55,
		power: 15,
	},
	{
		id: 181,
		name: 'Темный мертвец',
		range: 'melee',
		maxHp: 51,
		img: 'src/assets/DeadMan.png',
		damage: 30,
		hp: 51,
		power: 13,
	},
	{
		id: 182,
		name: 'Темный тролль',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/Troll.png',
		damage: 55,
		hp: 75,
		power: 21,
	},
	{
		id: 183,
		name: 'Темный элементаль',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Elemental.png',
		damage: 55,
		hp: 55,
		power: 20,
	},
	{
		id: 184,
		name: 'Темный хаос',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Chaos.png',
		damage: 80,
		hp: 100,
		power: 31,
	},
	{
		id: 185,
		name: 'Темный эльф',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Elf.png',
		damage: 55,
		hp: 60,
		power: 20,
	},
	{
		id: 186,
		name: 'Темный голем',
		range: 'melee',
		maxHp: 110,
		img: 'src/assets/Golem.png',
		damage: 60,
		hp: 110,
		power: 28,
	},
	{
		id: 187,
		name: 'Темный призрак',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Ghost.png',
		damage: 35,
		hp: 150,
		power: 32,
	},
	{
		id: 188,
		name: 'Темный маг',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Mage.png',
		damage: 65,
		hp: 60,
		power: 22,
	},
	{
		id: 189,
		name: 'Темный варвар',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/barbarian.png',
		damage: 55,
		hp: 100,
		power: 25,
	},
	{
		id: 190,
		name: 'Темный великан',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/IceGiant.png',
		damage: 60,
		hp: 150,
		power: 35,
	},
	{
		id: 191,
		name: 'Темный дракон',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/FlameDrago.png',
		damage: 70,
		hp: 150,
		power: 38,
	},
	{
		id: 192,
		name: 'Темный ящер',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Lizzard.png',
		damage: 80,
		hp: 55,
		power: 24,
	},
	{
		id: 193,
		name: 'Темный король',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/king.png',
		damage: 55,
		hp: 75,
		power: 21,
	},
	{
		id: 194,
		name: 'Темный демон',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Devil.png',
		damage: 80,
		hp: 150,
		power: 40,
	},
	{
		id: 195,
		name: 'Темный зверь',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/Beast.png',
		damage: 55,
		hp: 100,
		power: 25,
	},
	{
		id: 196,
		name: 'Темный лучник',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Archer.png',
		damage: 45,
		hp: 55,
		power: 18,
	},
	{
		id: 197,
		name: 'Темный рыцарь',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/DarkKnight.png',
		damage: 75,
		hp: 125,
		power: 33,
	},
	{
		id: 198,
		name: 'Ледяной скелет',
		range: 'melee',
		maxHp: 20,
		img: 'src/assets/ArchSkeleton.png',
		damage: 20,
		hp: 20,
		power: 6,
	},
	{
		id: 199,
		name: 'Ледяной мертвец',
		range: 'melee',
		maxHp: 16,
		img: 'src/assets/DeadMan.png',
		damage: 15,
		hp: 16,
		power: 5,
	},
	{
		id: 200,
		name: 'Ледяной тролль',
		range: 'melee',
		maxHp: 40,
		img: 'src/assets/Troll.png',
		damage: 40,
		hp: 40,
		power: 13,
	},
	{
		id: 201,
		name: 'Ледяной элементаль',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Elemental.png',
		damage: 40,
		hp: 20,
		power: 11,
	},
	{
		id: 202,
		name: 'Ледяной хаос',
		range: 'ranged',
		maxHp: 65,
		img: 'src/assets/Chaos.png',
		damage: 65,
		hp: 65,
		power: 23,
	},
	{
		id: 203,
		name: 'Ледяной эльф',
		range: 'ranged',
		maxHp: 25,
		img: 'src/assets/Elf.png',
		damage: 40,
		hp: 25,
		power: 12,
	},
	{
		id: 204,
		name: 'Ледяной голем',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/Golem.png',
		damage: 45,
		hp: 75,
		power: 20,
	},
	{
		id: 205,
		name: 'Ледяной призрак',
		range: 'ranged',
		maxHp: 115,
		img: 'src/assets/Ghost.png',
		damage: 20,
		hp: 115,
		power: 24,
	},
	{
		id: 206,
		name: 'Ледяной маг',
		range: 'ranged',
		maxHp: 25,
		img: 'src/assets/Mage.png',
		damage: 50,
		hp: 25,
		power: 14,
	},
	{
		id: 207,
		name: 'Ледяной варвар',
		range: 'melee',
		maxHp: 65,
		img: 'src/assets/barbarian.png',
		damage: 40,
		hp: 65,
		power: 17,
	},
	{
		id: 208,
		name: 'Ледяной великан',
		range: 'melee',
		maxHp: 115,
		img: 'src/assets/IceGiant.png',
		damage: 45,
		hp: 115,
		power: 26,
	},
	{
		id: 209,
		name: 'Ледяной дракон',
		range: 'ranged',
		maxHp: 115,
		img: 'src/assets/FlameDrago.png',
		damage: 55,
		hp: 115,
		power: 30,
	},
	{
		id: 210,
		name: 'Ледяной ящер',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Lizzard.png',
		damage: 65,
		hp: 20,
		power: 15,
	},
	{
		id: 211,
		name: 'Ледяной король',
		range: 'melee',
		maxHp: 40,
		img: 'src/assets/king.png',
		damage: 40,
		hp: 40,
		power: 13,
	},
	{
		id: 212,
		name: 'Ледяной демон',
		range: 'ranged',
		maxHp: 115,
		img: 'src/assets/Devil.png',
		damage: 65,
		hp: 115,
		power: 31,
	},
	{
		id: 213,
		name: 'Ледяной зверь',
		range: 'melee',
		maxHp: 65,
		img: 'src/assets/Beast.png',
		damage: 40,
		hp: 65,
		power: 17,
	},
	{
		id: 214,
		name: 'Ледяной лучник',
		range: 'ranged',
		maxHp: 20,
		img: 'src/assets/Archer.png',
		damage: 30,
		hp: 20,
		power: 10,
	},
	{
		id: 215,
		name: 'Ледяной рыцарь',
		range: 'melee',
		maxHp: 90,
		img: 'src/assets/DarkKnight.png',
		damage: 60,
		hp: 90,
		power: 25,
	},
	{
		id: 216,
		name: 'Святой скелет',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/ArchSkeleton.png',
		damage: 55,
		hp: 55,
		power: 18,
	},
	{
		id: 217,
		name: 'Святой мертвец',
		range: 'melee',
		maxHp: 51,
		img: 'src/assets/DeadMan.png',
		damage: 50,
		hp: 51,
		power: 16,
	},
	{
		id: 218,
		name: 'Святой тролль',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/Troll.png',
		damage: 75,
		hp: 75,
		power: 25,
	},
	{
		id: 219,
		name: 'Святой элементаль',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Elemental.png',
		damage: 75,
		hp: 55,
		power: 23,
	},
	{
		id: 220,
		name: 'Святой хаос',
		range: 'ranged',
		maxHp: 100,
		img: 'src/assets/Chaos.png',
		damage: 100,
		hp: 100,
		power: 35,
	},
	{
		id: 221,
		name: 'Святой эльф',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Elf.png',
		damage: 75,
		hp: 60,
		power: 24,
	},
	{
		id: 222,
		name: 'Святой голем',
		range: 'melee',
		maxHp: 110,
		img: 'src/assets/Golem.png',
		damage: 80,
		hp: 110,
		power: 31,
	},
	{
		id: 223,
		name: 'Святой призрак',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Ghost.png',
		damage: 55,
		hp: 150,
		power: 35,
	},
	{
		id: 224,
		name: 'Святой маг',
		range: 'ranged',
		maxHp: 60,
		img: 'src/assets/Mage.png',
		damage: 85,
		hp: 60,
		power: 25,
	},
	{
		id: 225,
		name: 'Святой варвар',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/barbarian.png',
		damage: 75,
		hp: 100,
		power: 29,
	},
	{
		id: 226,
		name: 'Святой великан',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/IceGiant.png',
		damage: 80,
		hp: 150,
		power: 38,
	},
	{
		id: 227,
		name: 'Святой дракон',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/FlameDrago.png',
		damage: 90,
		hp: 150,
		power: 41,
	},
	{
		id: 228,
		name: 'Святой ящер',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Lizzard.png',
		damage: 100,
		hp: 55,
		power: 27,
	},
	{
		id: 229,
		name: 'Святой король',
		range: 'melee',
		maxHp: 75,
		img: 'src/assets/king.png',
		damage: 75,
		hp: 75,
		power: 25,
	},
	{
		id: 230,
		name: 'Святой демон',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Devil.png',
		damage: 100,
		hp: 150,
		power: 43,
	},
	{
		id: 231,
		name: 'Святой зверь',
		range: 'melee',
		maxHp: 100,
		img: 'src/assets/Beast.png',
		damage: 75,
		hp: 100,
		power: 29,
	},
	{
		id: 232,
		name: 'Святой лучник',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Archer.png',
		damage: 65,
		hp: 55,
		power: 21,
	},
	{
		id: 233,
		name: 'Святой рыцарь',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/DarkKnight.png',
		damage: 95,
		hp: 125,
		power: 36,
	},
	{
		id: 234,
		name: 'Крепкий скелет',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/ArchSkeleton.png',
		damage: 5,
		hp: 105,
		power: 18,
	},
	{
		id: 235,
		name: 'Крепкий мертвец',
		range: 'melee',
		maxHp: 101,
		img: 'src/assets/DeadMan.png',
		hp: 101,
		power: 16,
		damage: 0,
	},
	{
		id: 236,
		name: 'Крепкий тролль',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/Troll.png',
		damage: 25,
		hp: 125,
		power: 25,
	},
	{
		id: 237,
		name: 'Крепкий элементаль',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Elemental.png',
		damage: 25,
		hp: 105,
		power: 23,
	},
	{
		id: 238,
		name: 'Крепкий хаос',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Chaos.png',
		damage: 50,
		hp: 150,
		power: 35,
	},
	{
		id: 239,
		name: 'Крепкий эльф',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Elf.png',
		damage: 25,
		hp: 110,
		power: 24,
	},
	{
		id: 240,
		name: 'Крепкий голем',
		range: 'melee',
		maxHp: 160,
		img: 'src/assets/Golem.png',
		damage: 30,
		hp: 160,
		power: 31,
	},
	{
		id: 241,
		name: 'Крепкий призрак',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/Ghost.png',
		damage: 5,
		hp: 200,
		power: 35,
	},
	{
		id: 242,
		name: 'Крепкий маг',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Mage.png',
		damage: 35,
		hp: 110,
		power: 25,
	},
	{
		id: 243,
		name: 'Крепкий варвар',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/barbarian.png',
		damage: 25,
		hp: 150,
		power: 29,
	},
	{
		id: 244,
		name: 'Крепкий великан',
		range: 'melee',
		maxHp: 200,
		img: 'src/assets/IceGiant.png',
		damage: 30,
		hp: 200,
		power: 38,
	},
	{
		id: 245,
		name: 'Крепкий дракон',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/FlameDrago.png',
		damage: 40,
		hp: 200,
		power: 41,
	},
	{
		id: 246,
		name: 'Крепкий ящер',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Lizzard.png',
		damage: 50,
		hp: 105,
		power: 27,
	},
	{
		id: 247,
		name: 'Крепкий король',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/king.png',
		damage: 25,
		hp: 125,
		power: 25,
	},
	{
		id: 248,
		name: 'Крепкий демон',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/Devil.png',
		damage: 50,
		hp: 200,
		power: 43,
	},
	{
		id: 249,
		name: 'Крепкий зверь',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/Beast.png',
		damage: 25,
		hp: 150,
		power: 29,
	},
	{
		id: 250,
		name: 'Крепкий лучник',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Archer.png',
		damage: 15,
		hp: 105,
		power: 21,
	},
	{
		id: 251,
		name: 'Крепкий рыцарь',
		range: 'melee',
		maxHp: 175,
		img: 'src/assets/DarkKnight.png',
		damage: 45,
		hp: 175,
		power: 36,
	},
	{
		id: 252,
		name: 'Горный скелет',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/ArchSkeleton.png',
		damage: 25,
		hp: 105,
		power: 21,
	},
	{
		id: 253,
		name: 'Горный мертвец',
		range: 'melee',
		maxHp: 101,
		img: 'src/assets/DeadMan.png',
		damage: 20,
		hp: 101,
		power: 20,
	},
	{
		id: 254,
		name: 'Горный тролль',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/Troll.png',
		damage: 45,
		hp: 125,
		power: 28,
	},
	{
		id: 255,
		name: 'Горный элементаль',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Elemental.png',
		damage: 45,
		hp: 105,
		power: 26,
	},
	{
		id: 256,
		name: 'Горный хаос',
		range: 'ranged',
		maxHp: 150,
		img: 'src/assets/Chaos.png',
		damage: 70,
		hp: 150,
		power: 38,
	},
	{
		id: 257,
		name: 'Горный эльф',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Elf.png',
		damage: 45,
		hp: 110,
		power: 27,
	},
	{
		id: 258,
		name: 'Горный голем',
		range: 'melee',
		maxHp: 160,
		img: 'src/assets/Golem.png',
		damage: 50,
		hp: 160,
		power: 35,
	},
	{
		id: 259,
		name: 'Горный призрак',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/Ghost.png',
		damage: 25,
		hp: 200,
		power: 39,
	},
	{
		id: 260,
		name: 'Горный маг',
		range: 'ranged',
		maxHp: 110,
		img: 'src/assets/Mage.png',
		damage: 55,
		hp: 110,
		power: 29,
	},
	{
		id: 261,
		name: 'Горный варвар',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/barbarian.png',
		damage: 45,
		hp: 150,
		power: 32,
	},
	{
		id: 262,
		name: 'Горный великан',
		range: 'melee',
		maxHp: 200,
		img: 'src/assets/IceGiant.png',
		damage: 50,
		hp: 200,
		power: 41,
	},
	{
		id: 263,
		name: 'Горный дракон',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/FlameDrago.png',
		damage: 60,
		hp: 200,
		power: 45,
	},
	{
		id: 264,
		name: 'Горный ящер',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Lizzard.png',
		damage: 70,
		hp: 105,
		power: 30,
	},
	{
		id: 265,
		name: 'Горный король',
		range: 'melee',
		maxHp: 125,
		img: 'src/assets/king.png',
		damage: 45,
		hp: 125,
		power: 28,
	},
	{
		id: 266,
		name: 'Горный демон',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/Devil.png',
		damage: 70,
		hp: 200,
		power: 46,
	},
	{
		id: 267,
		name: 'Горный зверь',
		range: 'melee',
		maxHp: 150,
		img: 'src/assets/Beast.png',
		damage: 45,
		hp: 150,
		power: 32,
	},
	{
		id: 268,
		name: 'Горный лучник',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Archer.png',
		damage: 35,
		hp: 105,
		power: 25,
	},
	{
		id: 269,
		name: 'Горный рыцарь',
		range: 'melee',
		maxHp: 175,
		img: 'src/assets/DarkKnight.png',
		damage: 65,
		hp: 175,
		power: 40,
	},
	{
		id: 270,
		name: 'Летающий скелет',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/ArchSkeleton.png',
		damage: -5,
		hp: 10,
		power: 2,
	},
	{
		id: 271,
		name: 'Летающий мертвец',
		range: 'ranged',
		maxHp: 6,
		img: 'src/assets/DeadMan.png',
		damage: -10,
		hp: 6,
		power: 1,
	},
	{
		id: 272,
		name: 'Летающий тролль',
		range: 'ranged',
		maxHp: 30,
		img: 'src/assets/Troll.png',
		damage: 15,
		hp: 30,
		power: 9,
	},
	{
		id: 273,
		name: 'Летающий элементаль',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Elemental.png',
		damage: 15,
		hp: 10,
		power: 7,
	},
	{
		id: 274,
		name: 'Летающий хаос',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Chaos.png',
		damage: 40,
		hp: 55,
		power: 19,
	},
	{
		id: 275,
		name: 'Летающий эльф',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Elf.png',
		damage: 15,
		hp: 15,
		power: 8,
	},
	{
		id: 276,
		name: 'Летающий голем',
		range: 'ranged',
		maxHp: 65,
		img: 'src/assets/Golem.png',
		damage: 20,
		hp: 65,
		power: 15,
	},
	{
		id: 277,
		name: 'Летающий призрак',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Ghost.png',
		damage: -5,
		hp: 105,
		power: 20,
	},
	{
		id: 278,
		name: 'Летающий маг',
		range: 'ranged',
		maxHp: 15,
		img: 'src/assets/Mage.png',
		damage: 25,
		hp: 15,
		power: 10,
	},
	{
		id: 279,
		name: 'Летающий варвар',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/barbarian.png',
		damage: 15,
		hp: 55,
		power: 13,
	},
	{
		id: 280,
		name: 'Летающий великан',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/IceGiant.png',
		damage: 20,
		hp: 105,
		power: 22,
	},
	{
		id: 281,
		name: 'Летающий дракон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/FlameDrago.png',
		damage: 30,
		hp: 105,
		power: 25,
	},
	{
		id: 282,
		name: 'Летающий ящер',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Lizzard.png',
		damage: 40,
		hp: 10,
		power: 11,
	},
	{
		id: 283,
		name: 'Летающий король',
		range: 'ranged',
		maxHp: 30,
		img: 'src/assets/king.png',
		damage: 15,
		hp: 30,
		power: 9,
	},
	{
		id: 284,
		name: 'Летающий демон',
		range: 'ranged',
		maxHp: 105,
		img: 'src/assets/Devil.png',
		damage: 40,
		hp: 105,
		power: 27,
	},
	{
		id: 285,
		name: 'Летающий зверь',
		range: 'ranged',
		maxHp: 55,
		img: 'src/assets/Beast.png',
		damage: 15,
		hp: 55,
		power: 13,
	},
	{
		id: 286,
		name: 'Летающий лучник',
		range: 'ranged',
		maxHp: 10,
		img: 'src/assets/Archer.png',
		damage: 5,
		hp: 10,
		power: 5,
	},
	{
		id: 287,
		name: 'Летающий рыцарь',
		range: 'ranged',
		maxHp: 80,
		img: 'src/assets/DarkKnight.png',
		damage: 35,
		hp: 80,
		power: 20,
	},
	{
		id: 288,
		name: 'Живой скелет',
		range: 'melee',
		maxHp: 35,
		img: 'src/assets/ArchSkeleton.png',
		damage: 35,
		hp: 35,
		power: 11,
	},
	{
		id: 289,
		name: 'Живой мертвец',
		range: 'melee',
		maxHp: 31,
		img: 'src/assets/DeadMan.png',
		damage: 30,
		hp: 31,
		power: 10,
	},
	{
		id: 290,
		name: 'Живой тролль',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/Troll.png',
		damage: 55,
		hp: 55,
		power: 18,
	},
	{
		id: 291,
		name: 'Живой элементаль',
		range: 'ranged',
		maxHp: 35,
		img: 'src/assets/Elemental.png',
		damage: 55,
		hp: 35,
		power: 16,
	},
	{
		id: 292,
		name: 'Живой хаос',
		range: 'ranged',
		maxHp: 80,
		img: 'src/assets/Chaos.png',
		damage: 80,
		hp: 80,
		power: 28,
	},
	{
		id: 293,
		name: 'Живой эльф',
		range: 'ranged',
		maxHp: 40,
		img: 'src/assets/Elf.png',
		damage: 55,
		hp: 40,
		power: 17,
	},
	{
		id: 294,
		name: 'Живой голем',
		range: 'melee',
		maxHp: 90,
		img: 'src/assets/Golem.png',
		damage: 60,
		hp: 90,
		power: 25,
	},
	{
		id: 295,
		name: 'Живой призрак',
		range: 'ranged',
		maxHp: 130,
		img: 'src/assets/Ghost.png',
		damage: 35,
		hp: 130,
		power: 29,
	},
	{
		id: 296,
		name: 'Живой маг',
		range: 'ranged',
		maxHp: 40,
		img: 'src/assets/Mage.png',
		damage: 65,
		hp: 40,
		power: 19,
	},
	{
		id: 297,
		name: 'Живой варвар',
		range: 'melee',
		maxHp: 80,
		img: 'src/assets/barbarian.png',
		damage: 55,
		hp: 80,
		power: 22,
	},
	{
		id: 298,
		name: 'Живой великан',
		range: 'melee',
		maxHp: 130,
		img: 'src/assets/IceGiant.png',
		damage: 60,
		hp: 130,
		power: 31,
	},
	{
		id: 299,
		name: 'Живой дракон',
		range: 'ranged',
		maxHp: 130,
		img: 'src/assets/FlameDrago.png',
		damage: 70,
		hp: 130,
		power: 35,
	},
	{
		id: 300,
		name: 'Живой ящер',
		range: 'ranged',
		maxHp: 35,
		img: 'src/assets/Lizzard.png',
		damage: 80,
		hp: 35,
		power: 20,
	},
	{
		id: 301,
		name: 'Живой король',
		range: 'melee',
		maxHp: 55,
		img: 'src/assets/king.png',
		damage: 55,
		hp: 55,
		power: 18,
	},
	{
		id: 302,
		name: 'Живой демон',
		range: 'ranged',
		maxHp: 130,
		img: 'src/assets/Devil.png',
		damage: 80,
		hp: 130,
		power: 36,
	},
	{
		id: 303,
		name: 'Живой зверь',
		range: 'melee',
		maxHp: 80,
		img: 'src/assets/Beast.png',
		damage: 55,
		hp: 80,
		power: 22,
	},
	{
		id: 304,
		name: 'Живой лучник',
		range: 'ranged',
		maxHp: 35,
		img: 'src/assets/Archer.png',
		damage: 45,
		hp: 35,
		power: 15,
	},
	{
		id: 305,
		name: 'Живой рыцарь',
		range: 'melee',
		maxHp: 105,
		img: 'src/assets/DarkKnight.png',
		damage: 75,
		hp: 105,
		power: 30,
	},
	{
		id: 306,
		name: 'Элитный скелет',
		range: 'melee',
		maxHp: 155,
		img: 'src/assets/ArchSkeleton.png',
		damage: 55,
		hp: 155,
		power: 35,
	},
	{
		id: 307,
		name: 'Элитный мертвец',
		range: 'melee',
		maxHp: 151,
		img: 'src/assets/DeadMan.png',
		damage: 50,
		hp: 151,
		power: 33,
	},
	{
		id: 308,
		name: 'Элитный тролль',
		range: 'melee',
		maxHp: 175,
		img: 'src/assets/Troll.png',
		damage: 75,
		hp: 175,
		power: 41,
	},
	{
		id: 309,
		name: 'Элитный элементаль',
		range: 'ranged',
		maxHp: 155,
		img: 'src/assets/Elemental.png',
		damage: 75,
		hp: 155,
		power: 40,
	},
	{
		id: 310,
		name: 'Элитный хаос',
		range: 'ranged',
		maxHp: 200,
		img: 'src/assets/Chaos.png',
		damage: 100,
		hp: 200,
		power: 51,
	},
	{
		id: 311,
		name: 'Элитный эльф',
		range: 'ranged',
		maxHp: 160,
		img: 'src/assets/Elf.png',
		damage: 75,
		hp: 160,
		power: 40,
	},
	{
		id: 312,
		name: 'Элитный голем',
		range: 'melee',
		maxHp: 210,
		img: 'src/assets/Golem.png',
		damage: 80,
		hp: 210,
		power: 48,
	},
	{
		id: 313,
		name: 'Элитный призрак',
		range: 'ranged',
		maxHp: 250,
		img: 'src/assets/Ghost.png',
		damage: 55,
		hp: 250,
		power: 52,
	},
	{
		id: 314,
		name: 'Элитный маг',
		range: 'ranged',
		maxHp: 160,
		img: 'src/assets/Mage.png',
		damage: 85,
		hp: 160,
		power: 42,
	},
	{
		id: 315,
		name: 'Элитный варвар',
		range: 'melee',
		maxHp: 200,
		img: 'src/assets/barbarian.png',
		damage: 75,
		hp: 200,
		power: 45,
	},
	{
		id: 316,
		name: 'Элитный великан',
		range: 'melee',
		maxHp: 250,
		img: 'src/assets/IceGiant.png',
		damage: 80,
		hp: 250,
		power: 55,
	},
	{
		id: 317,
		name: 'Элитный дракон',
		range: 'ranged',
		maxHp: 250,
		img: 'src/assets/FlameDrago.png',
		damage: 90,
		hp: 250,
		power: 58,
	},
	{
		id: 318,
		name: 'Элитный ящер',
		range: 'ranged',
		maxHp: 155,
		img: 'src/assets/Lizzard.png',
		damage: 100,
		hp: 155,
		power: 44,
	},
	{
		id: 319,
		name: 'Элитный король',
		range: 'melee',
		maxHp: 175,
		img: 'src/assets/king.png',
		damage: 75,
		hp: 175,
		power: 41,
	},
	{
		id: 320,
		name: 'Элитный демон',
		range: 'ranged',
		maxHp: 250,
		img: 'src/assets/Devil.png',
		damage: 100,
		hp: 250,
		power: 60,
	},
	{
		id: 321,
		name: 'Элитный зверь',
		range: 'melee',
		maxHp: 200,
		img: 'src/assets/Beast.png',
		damage: 75,
		hp: 200,
		power: 45,
	},
	{
		id: 322,
		name: 'Элитный лучник',
		range: 'ranged',
		maxHp: 155,
		img: 'src/assets/Archer.png',
		damage: 65,
		hp: 155,
		power: 38,
	},
	{
		id: 323,
		name: 'Элитный рыцарь',
		range: 'melee',
		maxHp: 225,
		img: 'src/assets/DarkKnight.png',
		damage: 95,
		hp: 225,
		power: 53,
	},
	//#######################----BOSSES----###########################
	{
		id: 324,
		name: 'Дракон Апокалипсиса',
		range: 'ranged',
		maxHp: 175,
		damage: 85,
		hp: 175,
		power: 45,
	},
	{
		id: 325,
		name: 'Дракон Хаоса',
		range: 'ranged',
		maxHp: 150,
		damage: 85,
		hp: 150,
		power: 40,
	},
	{
		id: 326,
		name: 'Дракон Ада',
		range: 'ranged',
		maxHp: 150,
		damage: 110,
		hp: 150,
		power: 45,
	},
	{
		id: 327,
		name: 'Дракон Вселенной',
		range: 'ranged',
		maxHp: 225,
		damage: 110,
		hp: 225,
		power: 57,
	},
	{
		id: 328,
		name: 'Дракон мрака',
		range: 'ranged',
		maxHp: 225,
		damage: 85,
		hp: 225,
		power: 53,
	},
	{
		id: 329,
		name: 'Дракон королевства мёртвых',
		range: 'ranged',
		maxHp: 225,
		damage: 110,
		hp: 225,
		power: 57,
	},
	{
		id: 330,
		name: 'Дракон страха',
		range: 'ranged',
		maxHp: 275,
		damage: 85,
		hp: 275,
		power: 61,
	},
	{
		id: 331,
		name: 'Лич Апокалипсиса',
		range: 'melee',
		maxHp: 150,
		damage: 100,
		hp: 150,
		power: 41,
	},
	{
		id: 332,
		name: 'Лич Хаоса',
		range: 'melee',
		maxHp: 125,
		damage: 100,
		hp: 125,
		power: 37,
	},
	{
		id: 333,
		name: 'Лич Ада',
		range: 'melee',
		maxHp: 125,
		damage: 125,
		hp: 125,
		power: 41,
	},
	{
		id: 334,
		name: 'Лич Вселенной',
		range: 'melee',
		maxHp: 200,
		damage: 125,
		hp: 200,
		power: 54,
	},
	{
		id: 335,
		name: 'Лич мрака',
		range: 'melee',
		maxHp: 200,
		damage: 100,
		hp: 200,
		power: 50,
	},
	{
		id: 336,
		name: 'Лич королевства мёртвых',
		range: 'melee',
		maxHp: 200,
		damage: 125,
		hp: 200,
		power: 54,
	},
	{
		id: 337,
		name: 'Лич страха',
		range: 'melee',
		maxHp: 250,
		damage: 100,
		hp: 250,
		power: 58,
	},
	{
		id: 338,
		name: 'Архидемон Апокалипсиса',
		range: 'melee',
		maxHp: 225,
		damage: 120,
		hp: 225,
		power: 57,
	},
	{
		id: 339,
		name: 'Архидемон Хаоса',
		range: 'melee',
		maxHp: 200,
		damage: 120,
		hp: 200,
		power: 53,
	},
	{
		id: 340,
		name: 'Архидемон Ада',
		range: 'melee',
		maxHp: 200,
		damage: 145,
		hp: 200,
		power: 57,
	},
	{
		id: 341,
		name: 'Архидемон Вселенной',
		range: 'melee',
		maxHp: 275,
		damage: 145,
		hp: 275,
		power: 70,
	},
	{
		id: 342,
		name: 'Архидемон мрака',
		range: 'melee',
		maxHp: 275,
		damage: 120,
		hp: 275,
		power: 65,
	},
	{
		id: 343,
		name: 'Архидемон королевства мёртвых',
		range: 'melee',
		maxHp: 275,
		damage: 145,
		hp: 275,
		power: 70,
	},
	{
		id: 344,
		name: 'Архидемон страха',
		range: 'melee',
		maxHp: 325,
		damage: 120,
		hp: 325,
		power: 74,
	},
	{
		id: 345,
		name: 'Судья Апокалипсиса',
		range: 'melee',
		maxHp: 150,
		damage: 100,
		hp: 150,
		power: 41,
	},
	{
		id: 346,
		name: 'Судья Хаоса',
		range: 'melee',
		maxHp: 125,
		damage: 100,
		hp: 125,
		power: 37,
	},
	{
		id: 347,
		name: 'Судья Ада',
		range: 'melee',
		maxHp: 125,
		damage: 125,
		hp: 125,
		power: 41,
	},
	{
		id: 348,
		name: 'Судья Вселенной',
		range: 'melee',
		maxHp: 200,
		damage: 125,
		hp: 200,
		power: 54,
	},
	{
		id: 349,
		name: 'Судья мрака',
		range: 'melee',
		maxHp: 200,
		damage: 100,
		hp: 200,
		power: 50,
	},
	{
		id: 350,
		name: 'Судья королевства мёртвых',
		range: 'melee',
		maxHp: 200,
		damage: 125,
		hp: 200,
		power: 54,
	},
	{
		id: 351,
		name: 'Судья страха',
		range: 'melee',
		maxHp: 250,
		damage: 100,
		hp: 250,
		power: 58,
	},
	{
		id: 352,
		name: 'Тень Апокалипсиса',
		range: 'ranged',
		maxHp: 125,
		damage: 125,
		hp: 125,
		power: 43,
	},
	{
		id: 353,
		name: 'Тень Хаоса',
		range: 'ranged',
		maxHp: 100,
		damage: 125,
		hp: 100,
		power: 39,
	},
	{
		id: 354,
		name: 'Тень Ада',
		range: 'ranged',
		maxHp: 100,
		damage: 150,
		hp: 100,
		power: 43,
	},
	{
		id: 355,
		name: 'Тень Вселенной',
		range: 'ranged',
		maxHp: 175,
		damage: 150,
		hp: 175,
		power: 55,
	},
	{
		id: 356,
		name: 'Тень мрака',
		range: 'ranged',
		maxHp: 175,
		damage: 125,
		hp: 175,
		power: 51,
	},
	{
		id: 357,
		name: 'Тень королевства мёртвых',
		range: 'ranged',
		maxHp: 175,
		damage: 150,
		hp: 175,
		power: 55,
	},
	{
		id: 358,
		name: 'Тень страха',
		range: 'ranged',
		maxHp: 225,
		damage: 125,
		hp: 225,
		power: 60,
	},
	{
		id: 359,
		name: 'Гидра Апокалипсиса',
		range: 'ranged',
		maxHp: 250,
		damage: 80,
		hp: 250,
		power: 56,
	},
	{
		id: 360,
		name: 'Гидра Хаоса',
		range: 'ranged',
		maxHp: 225,
		damage: 80,
		hp: 225,
		power: 52,
	},
	{
		id: 361,
		name: 'Гидра Ада',
		range: 'ranged',
		maxHp: 225,
		damage: 105,
		hp: 225,
		power: 56,
	},
	{
		id: 362,
		name: 'Гидра Вселенной',
		range: 'ranged',
		maxHp: 300,
		damage: 105,
		hp: 300,
		power: 69,
	},
	{
		id: 363,
		name: 'Гидра мрака',
		range: 'ranged',
		maxHp: 300,
		damage: 80,
		hp: 300,
		power: 65,
	},
	{
		id: 364,
		name: 'Гидра королевства мёртвых',
		range: 'ranged',
		maxHp: 300,
		damage: 105,
		hp: 300,
		power: 69,
	},
	{
		id: 365,
		name: 'Гидра страха',
		range: 'ranged',
		maxHp: 350,
		damage: 80,
		hp: 350,
		power: 73,
	},
]

export default enemies
