import { ItemType } from "../types/types";

export const getRandomItemId = (rare?: 'basic' | 'rare' | 'epic' | 'legendary') => {
	if (!rare) return Math.floor(Math.random() * (items.length - 1))
	const rareItems = findByProperty(items, 'rare', rare);
	const item = rareItems[Math.floor(Math.random() * (rareItems.length - 1))];
	return item.id;
}

function findByProperty(array: Array<any>, property: string, value: any) {
	const results = []
	for (const object of array) {
		if (object[property] === value) {
			results.push(object)
		}
	}
	return results
}

export const items: ItemType[] =[
	{id: 0,name: 'Меч бури',damage: 10,fortune: -5,type: 'weapon',massDamage: 30,rare: 'rare'},
	{id: 1,name: 'Меч пламени',damage: 15,fortune: -5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 2,name: 'Меч быстроты',damage: 5,agility: 5,type: 'weapon',rare: 'basic'},
	{id: 3,name: 'Меч ловкости',damage: 5,agility: 10,type: 'weapon',rare: 'basic'},
	{id: 4,name: 'Меч тени',damage: 20,agility: -10,fortune: -10,shield: 20,type: 'weapon',rare: 'rare'},
	{id: 5,name: 'Меч демона',damage: 15,agility: 5,fortune: -30,shield: -10,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 6,name: 'Меч невидимости',damage: 5,agility: 15,shield: 15,type: 'weapon',rare: 'epic'},
	{id: 7,name: 'Меч удачи',damage: 5,fortune: 20,type: 'weapon',rare: 'basic'},
	{id: 8,name: 'Меч яда',damage: 35,shield: -50,type: 'weapon',rare: 'epic'},
	{id: 9,name: 'Меч героя',damage: 15,agility: 10,fortune: 10,shield: 10,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 10,name: 'Меч мудрости',damage: -5,fortune: 20,type: 'weapon',rare: 'rare'},
	{id: 11,name: 'Меч Короля',damage: 15,fortune: 10,shield: -5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 12,name: 'Меч силы',damage: 25,agility: 10,fortune: -5,shield: -5,type: 'weapon',rare: 'epic'},
	{id: 13,name: 'Меч берсерка',damage: 25,agility: -50,shield: -20,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 14,name: 'Меч древних',damage: -15,agility: 20,fortune: 20,shield: 20,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 15,name: 'Меч ',damage: 5,type: 'weapon',rare: 'basic'},
	{id: 16,name: 'Секира бури',damage: 10,fortune: -5,type: 'weapon',massDamage: 40,rare: 'rare'},
	{id: 17,name: 'Секира пламени',damage: 15,fortune: -5,type: 'weapon',massDamage: 20,rare: 'rare'},
	{id: 18,name: 'Секира быстроты',damage: 5,agility: 5,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 19,name: 'Секира ловкости',damage: 5,agility: 10,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 20,name: 'Секира тени',damage: 20,agility: -10,fortune: -10,shield: 20,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 21,name: 'Секира демона',damage: 15,agility: 5,fortune: -30,shield: -10,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 22,name: 'Секира невидимости',damage: 5,agility: 15,shield: 15,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 23,name: 'Секира удачи',damage: 5,fortune: 20,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 24,name: 'Секира яда',damage: 35,shield: -50,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 25,name: 'Секира героя',damage: 15,agility: 10,fortune: 10,shield: 10,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 26,name: 'Секира мудрости',damage: -5,fortune: 20,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 27,name: 'Секира Короля',damage: 15,fortune: 10,shield: -5,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 28,name: 'Секира силы',damage: 25,agility: 10,fortune: -5,shield: -5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 29,name: 'Секира берсерка',damage: 25,agility: -50,shield: -20,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 30,name: 'Секира древних',damage: -15,agility: 20,fortune: 20,shield: 20,type: 'weapon',massDamage: 30,rare: 'epic'},
	{id: 31,name: 'Секира ',damage: 5,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 32,name: 'Топоры бури',damage: 15,fortune: -5,type: 'weapon',massDamage: 30,rare: 'rare'},
	{id: 33,name: 'Топоры пламени',damage: 20,fortune: -5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 34,name: 'Топоры быстроты',damage: 10,agility: 5,type: 'weapon',rare: 'basic'},
	{id: 35,name: 'Топоры ловкости',damage: 10,agility: 10,type: 'weapon',rare: 'basic'},
	{id: 36,name: 'Топоры тени',damage: 25,agility: -10,fortune: -10,shield: 20,type: 'weapon',rare: 'rare'},
	{id: 37,name: 'Топоры демона',damage: 20,agility: 5,fortune: -30,shield: -10,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 38,name: 'Топоры невидимости',damage: 10,agility: 15,shield: 15,type: 'weapon',rare: 'epic'},
	{id: 39,name: 'Топоры удачи',damage: 10,fortune: 20,type: 'weapon',rare: 'basic'},
	{id: 40,name: 'Топоры яда',damage: 40,shield: -50,type: 'weapon',rare: 'epic'},
	{id: 41,name: 'Топоры героя',damage: 20,agility: 10,fortune: 10,shield: 10,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 42,name: 'Топоры мудрости',fortune: 20,type: 'weapon',rare: 'rare'},
	{id: 43,name: 'Топоры Короля',damage: 20,fortune: 10,shield: -5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 44,name: 'Топоры силы',damage: 30,agility: 10,fortune: -5,shield: -5,type: 'weapon',rare: 'epic'},
	{id: 45,name: 'Топоры берсерка',damage: 30,agility: -50,shield: -20,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 46,name: 'Топоры древних',damage: -10,agility: 20,fortune: 20,shield: 20,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 47,name: 'Топоры ',damage: 10,type: 'weapon',rare: 'basic'},
	{id: 48,name: 'Посох бури',damage: 10,fortune: 5,type: 'weapon',massDamage: 40,rare: 'rare'},
	{id: 49,name: 'Посох пламени',damage: 15,fortune: 5,type: 'weapon',massDamage: 20,rare: 'rare'},
	{id: 50,name: 'Посох быстроты',damage: 5,agility: 5,fortune: 10,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 51,name: 'Посох ловкости',damage: 5,agility: 10,fortune: 10,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 52,name: 'Посох тени',damage: 20,agility: -10,shield: 20,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 53,name: 'Посох демона',damage: 15,agility: 5,fortune: -20,shield: -10,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 54,name: 'Посох невидимости',damage: 5,agility: 15,fortune: 10,shield: 15,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 55,name: 'Посох удачи',damage: 5,fortune: 30,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 56,name: 'Посох яда',damage: 35,fortune: 10,shield: -50,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 57,name: 'Посох героя',damage: 15,agility: 10,fortune: 20,shield: 10,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 58,name: 'Посох мудрости',damage: -5,fortune: 30,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 59,name: 'Посох Короля',damage: 15,fortune: 20,shield: -5,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 60,name: 'Посох силы',damage: 25,agility: 10,fortune: 5,shield: -5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 61,name: 'Посох берсерка',damage: 25,agility: -50,fortune: 10,shield: -20,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 62,name: 'Посох древних',damage: -15,agility: 20,fortune: 30,shield: 20,type: 'weapon',massDamage: 30,rare: 'epic'},
	{id: 63,name: 'Посох ',damage: 5,fortune: 10,type: 'weapon',massDamage: 10,rare: 'basic'},
	{id: 64,name: 'Щит бури',damage: 5,fortune: -5,shield: 10,type: 'shield',massDamage: 30,rare: 'rare'},
	{id: 65,name: 'Щит пламени',damage: 10,fortune: -5,shield: 10,type: 'shield',massDamage: 10,rare: 'rare'},
	{id: 66,name: 'Щит быстроты',agility: 5,shield: 10,type: 'shield',rare: 'basic'},
	{id: 67,name: 'Щит ловкости',agility: 10,shield: 10,type: 'shield',rare: 'basic'},
	{id: 68,name: 'Щит тени',damage: 15,agility: -10,fortune: -10,shield: 30,type: 'shield',rare: 'rare'},
	{id: 69,name: 'Щит демона',damage: 10,agility: 5,fortune: -30,type: 'shield',massDamage: 10,rare: 'epic'},
	{id: 70,name: 'Щит невидимости',agility: 15,shield: 25,type: 'shield',rare: 'epic'},
	{id: 71,name: 'Щит удачи',fortune: 20,shield: 10,type: 'shield',rare: 'basic'},
	{id: 72,name: 'Щит яда',damage: 30,shield: -40,type: 'shield',rare: 'epic'},
	{id: 73,name: 'Щит героя',damage: 10,agility: 10,fortune: 10,shield: 20,type: 'shield',massDamage: 10,rare: 'epic'},
	{id: 74,name: 'Щит мудрости',damage: -10,fortune: 20,shield: 10,type: 'shield',rare: 'rare'},
	{id: 75,name: 'Щит Короля',damage: 10,fortune: 10,shield: 5,type: 'shield',massDamage: 10,rare: 'epic'},
	{id: 76,name: 'Щит силы',damage: 20,agility: 10,fortune: -5,shield: 5,type: 'shield',rare: 'epic'},
	{id: 77,name: 'Щит берсерка',damage: 20,agility: -50,shield: -10,type: 'shield',massDamage: 10,rare: 'epic'},
	{id: 78,name: 'Щит древних',damage: -20,agility: 20,fortune: 20,shield: 30,type: 'shield',massDamage: 20,rare: 'epic'},
	{id: 79,name: 'Щит ',shield: 10,type: 'shield',rare: 'basic'},
	{id: 80,name: 'Баррикада бури',damage: 5,fortune: -5,shield: 20,type: 'shield',massDamage: 30,rare: 'epic'},
	{id: 81,name: 'Баррикада пламени',damage: 10,fortune: -5,shield: 20,type: 'shield',massDamage: 10,rare: 'epic'},
	{id: 82,name: 'Баррикада быстроты',agility: 5,shield: 20,type: 'shield',rare: 'rare'},
	{id: 83,name: 'Баррикада ловкости',agility: 10,shield: 20,type: 'shield',rare: 'rare'},
	{id: 84,name: 'Баррикада тени',damage: 15,agility: -10,fortune: -10,shield: 40,type: 'shield',rare: 'epic'},
	{id: 85,name: 'Баррикада демона',damage: 10,agility: 5,fortune: -30,shield: 10,type: 'shield',massDamage: 10,rare: 'legendary'},
	{id: 86,name: 'Баррикада невидимости',agility: 15,shield: 35,type: 'shield',rare: 'legendary'},
	{id: 87,name: 'Баррикада удачи',fortune: 20,shield: 20,type: 'shield',rare: 'rare'},
	{id: 88,name: 'Баррикада яда',damage: 30,shield: -30,type: 'shield',rare: 'legendary'},
	{id: 89,name: 'Баррикада героя',damage: 10,agility: 10,fortune: 10,shield: 30,type: 'shield',massDamage: 10,rare: 'legendary'},
	{id: 90,name: 'Баррикада мудрости',damage: -10,fortune: 20,shield: 20,type: 'shield',rare: 'epic'},
	{id: 91,name: 'Баррикада Короля',damage: 10,fortune: 10,shield: 15,type: 'shield',massDamage: 10,rare: 'legendary'},
	{id: 92,name: 'Баррикада силы',damage: 20,agility: 10,fortune: -5,shield: 15,type: 'shield',rare: 'legendary'},
	{id: 93,name: 'Баррикада берсерка',damage: 20,agility: -50,type: 'shield',massDamage: 10,rare: 'legendary'},
	{id: 94,name: 'Баррикада древних',damage: -20,agility: 20,fortune: 20,shield: 40,type: 'shield',massDamage: 20,rare: 'legendary'},
	{id: 95,name: 'Баррикада ',shield: 20,type: 'shield',rare: 'rare'},
	{id: 96,name: 'Лук бури',damage: 10,agility: 10,fortune: -5,type: 'weapon',massDamage: 30,rare: 'rare'},
	{id: 97,name: 'Лук пламени',damage: 15,agility: 10,fortune: -5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 98,name: 'Лук быстроты',damage: 5,agility: 15,type: 'weapon',rare: 'basic'},
	{id: 99,name: 'Лук ловкости',damage: 5,agility: 20,type: 'weapon',rare: 'basic'},
	{id: 100,name: 'Лук тени',damage: 20,fortune: -10,shield: 20,type: 'weapon',rare: 'rare'},
	{id: 101,name: 'Лук демона',damage: 15,agility: 15,fortune: -30,shield: -10,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 102,name: 'Лук невидимости',damage: 5,agility: 25,shield: 15,type: 'weapon',rare: 'epic'},
	{id: 103,name: 'Лук удачи',damage: 5,agility: 10,fortune: 20,type: 'weapon',rare: 'basic'},
	{id: 104,name: 'Лук яда',damage: 35,agility: 10,shield: -50,type: 'weapon',rare: 'epic'},
	{id: 105,name: 'Лук героя',damage: 15,agility: 20,fortune: 10,shield: 10,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 106,name: 'Лук мудрости',damage: -5,agility: 10,fortune: 20,type: 'weapon',rare: 'rare'},
	{id: 107,name: 'Лук Короля',damage: 15,agility: 10,fortune: 10,shield: -5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 108,name: 'Лук силы',damage: 25,agility: 20,fortune: -5,shield: -5,type: 'weapon',rare: 'epic'},
	{id: 109,name: 'Лук берсерка',damage: 25,agility: -40,shield: -20,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 110,name: 'Лук древних',damage: -15,agility: 30,fortune: 20,shield: 20,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 111,name: 'Лук ',damage: 5,agility: 10,type: 'weapon',rare: 'basic'},
	{id: 112,name: 'Двуручный меч бури',damage: 15,fortune: -5,shield: 5,type: 'weapon',massDamage: 40,rare: 'epic'},
	{id: 113,name: 'Двуручный меч пламени',damage: 20,fortune: -5,shield: 5,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 114,name: 'Двуручный меч быстроты',damage: 10,agility: 5,shield: 5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 115,name: 'Двуручный меч ловкости',damage: 10,agility: 10,shield: 5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 116,name: 'Двуручный меч тени',damage: 25,agility: -10,fortune: -10,shield: 25,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 117,name: 'Двуручный меч демона',damage: 20,agility: 5,fortune: -30,shield: -5,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 118,name: 'Двуручный меч невидимости',damage: 10,agility: 15,shield: 20,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 119,name: 'Двуручный меч удачи',damage: 10,fortune: 20,shield: 5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 120,name: 'Двуручный меч яда',damage: 40,shield: -45,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 121,name: 'Двуручный меч героя',damage: 20,agility: 10,fortune: 10,shield: 15,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 122,name: 'Двуручный меч мудрости',fortune: 20,shield: 5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 123,name: 'Двуручный меч Короля',damage: 20,fortune: 10,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 124,name: 'Двуручный меч силы',damage: 30,agility: 10,fortune: -5,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 125,name: 'Двуручный меч берсерка',damage: 30,agility: -50,shield: -15,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 126,name: 'Двуручный меч древних',damage: -10,agility: 20,fortune: 20,shield: 25,type: 'weapon',massDamage: 30,rare: 'legendary'},
	{id: 127,name: 'Двуручный меч ',damage: 10,shield: 5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 128,name: 'Кираса бури',damage: 5,agility: -5,fortune: -5,shield: 10,type: 'chest',massDamage: 30,rare: 'rare'},
	{id: 129,name: 'Кираса пламени',damage: 10,agility: -5,fortune: -5,shield: 10,type: 'chest',massDamage: 10,rare: 'rare'},
	{id: 130,name: 'Кираса быстроты',shield: 10,type: 'chest',rare: 'basic'},
	{id: 131,name: 'Кираса ловкости',agility: 5,shield: 10,type: 'chest',rare: 'basic'},
	{id: 132,name: 'Кираса тени',damage: 15,agility: -15,fortune: -10,shield: 30,type: 'chest',rare: 'rare'},
	{id: 133,name: 'Кираса демона',damage: 10,fortune: -30,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 134,name: 'Кираса невидимости',agility: 10,shield: 25,type: 'chest',rare: 'epic'},
	{id: 135,name: 'Кираса удачи',agility: -5,fortune: 20,shield: 10,type: 'chest',rare: 'basic'},
	{id: 136,name: 'Кираса яда',damage: 30,agility: -5,shield: -40,type: 'chest',rare: 'epic'},
	{id: 137,name: 'Кираса героя',damage: 10,agility: 5,fortune: 10,shield: 20,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 138,name: 'Кираса мудрости',damage: -10,agility: -5,fortune: 20,shield: 10,type: 'chest',rare: 'rare'},
	{id: 139,name: 'Кираса Короля',damage: 10,agility: -5,fortune: 10,shield: 5,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 140,name: 'Кираса силы',damage: 20,agility: 5,fortune: -5,shield: 5,type: 'chest',rare: 'epic'},
	{id: 141,name: 'Кираса берсерка',damage: 20,agility: -55,shield: -10,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 142,name: 'Кираса древних',damage: -20,agility: 15,fortune: 20,shield: 30,type: 'chest',massDamage: 20,rare: 'epic'},
	{id: 143,name: 'Кираса ',agility: -5,shield: 10,type: 'chest',rare: 'basic'},
	{id: 144,name: 'Шлем бури',damage: 5,fortune: -5,shield: 5,type: 'hat',massDamage: 30,rare: 'rare'},
	{id: 145,name: 'Шлем пламени',damage: 10,fortune: -5,shield: 5,type: 'hat',massDamage: 10,rare: 'rare'},
	{id: 146,name: 'Шлем быстроты',agility: 5,shield: 5,type: 'hat',rare: 'basic'},
	{id: 147,name: 'Шлем ловкости',agility: 10,shield: 5,type: 'hat',rare: 'basic'},
	{id: 148,name: 'Шлем тени',damage: 15,agility: -10,fortune: -10,shield: 25,type: 'hat',rare: 'rare'},
	{id: 149,name: 'Шлем демона',damage: 10,agility: 5,fortune: -30,shield: -5,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 150,name: 'Шлем невидимости',agility: 15,shield: 20,type: 'hat',rare: 'epic'},
	{id: 151,name: 'Шлем удачи',fortune: 20,shield: 5,type: 'hat',rare: 'basic'},
	{id: 152,name: 'Шлем яда',damage: 30,shield: -45,type: 'hat',rare: 'epic'},
	{id: 153,name: 'Шлем героя',damage: 10,agility: 10,fortune: 10,shield: 15,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 154,name: 'Шлем мудрости',damage: -10,fortune: 20,shield: 5,type: 'hat',rare: 'rare'},
	{id: 155,name: 'Шлем Короля',damage: 10,fortune: 10,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 156,name: 'Шлем силы',damage: 20,agility: 10,fortune: -5,type: 'hat',rare: 'epic'},
	{id: 157,name: 'Шлем берсерка',damage: 20,agility: -50,shield: -15,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 158,name: 'Шлем древних',damage: -20,agility: 20,fortune: 20,shield: 25,type: 'hat',massDamage: 20,rare: 'epic'},
	{id: 159,name: 'Шлем ',shield: 5,type: 'hat',rare: 'basic'},
	{id: 160,name: 'Шляпа бури',damage: 5,fortune: 5,type: 'hat',massDamage: 30,rare: 'rare'},
	{id: 161,name: 'Шляпа пламени',damage: 10,fortune: 5,type: 'hat',massDamage: 10,rare: 'rare'},
	{id: 162,name: 'Шляпа быстроты',agility: 5,fortune: 10,type: 'hat',rare: 'basic'},
	{id: 163,name: 'Шляпа ловкости',agility: 10,fortune: 10,type: 'hat',rare: 'basic'},
	{id: 164,name: 'Шляпа тени',damage: 15,agility: -10,shield: 20,type: 'hat',rare: 'rare'},
	{id: 165,name: 'Шляпа демона',damage: 10,agility: 5,fortune: -20,shield: -10,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 166,name: 'Шляпа невидимости',agility: 15,fortune: 10,shield: 15,type: 'hat',rare: 'epic'},
	{id: 167,name: 'Шляпа удачи',fortune: 30,type: 'hat',rare: 'basic'},
	{id: 168,name: 'Шляпа яда',damage: 30,fortune: 10,shield: -50,type: 'hat',rare: 'epic'},
	{id: 169,name: 'Шляпа героя',damage: 10,agility: 10,fortune: 20,shield: 10,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 170,name: 'Шляпа мудрости',damage: -10,fortune: 30,type: 'hat',rare: 'rare'},
	{id: 171,name: 'Шляпа Короля',damage: 10,fortune: 20,shield: -5,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 172,name: 'Шляпа силы',damage: 20,agility: 10,fortune: 5,shield: -5,type: 'hat',rare: 'epic'},
	{id: 173,name: 'Шляпа берсерка',damage: 20,agility: -50,fortune: 10,shield: -20,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 174,name: 'Шляпа древних',damage: -20,agility: 20,fortune: 30,shield: 20,type: 'hat',massDamage: 20,rare: 'epic'},
	{id: 175,name: 'Шляпа ',fortune: 10,type: 'hat',rare: 'basic'},
	{id: 176,name: 'Поножи бури',damage: 5,fortune: -5,shield: 5,type: 'pants',massDamage: 30,rare: 'rare'},
	{id: 177,name: 'Поножи пламени',damage: 10,fortune: -5,shield: 5,type: 'pants',massDamage: 10,rare: 'rare'},
	{id: 178,name: 'Поножи быстроты',agility: 5,shield: 5,type: 'pants',rare: 'basic'},
	{id: 179,name: 'Поножи ловкости',agility: 10,shield: 5,type: 'pants',rare: 'basic'},
	{id: 180,name: 'Поножи тени',damage: 15,agility: -10,fortune: -10,shield: 25,type: 'pants',rare: 'rare'},
	{id: 181,name: 'Поножи демона',damage: 10,agility: 5,fortune: -30,shield: -5,type: 'pants',massDamage: 10,rare: 'epic'},
	{id: 182,name: 'Поножи невидимости',agility: 15,shield: 20,type: 'pants',rare: 'epic'},
	{id: 183,name: 'Поножи удачи',fortune: 20,shield: 5,type: 'pants',rare: 'basic'},
	{id: 184,name: 'Поножи яда',damage: 30,shield: -45,type: 'pants',rare: 'epic'},
	{id: 185,name: 'Поножи героя',damage: 10,agility: 10,fortune: 10,shield: 15,type: 'pants',massDamage: 10,rare: 'epic'},
	{id: 186,name: 'Поножи мудрости',damage: -10,fortune: 20,shield: 5,type: 'pants',rare: 'rare'},
	{id: 187,name: 'Поножи Короля',damage: 10,fortune: 10,type: 'pants',massDamage: 10,rare: 'epic'},
	{id: 188,name: 'Поножи силы',damage: 20,agility: 10,fortune: -5,type: 'pants',rare: 'epic'},
	{id: 189,name: 'Поножи берсерка',damage: 20,agility: -50,shield: -15,type: 'pants',massDamage: 10,rare: 'epic'},
	{id: 190,name: 'Поножи древних',damage: -20,agility: 20,fortune: 20,shield: 25,type: 'pants',massDamage: 20,rare: 'epic'},
	{id: 191,name: 'Поножи ',shield: 5,type: 'pants',rare: 'basic'},
	{id: 192,name: 'Сабатоны бури',damage: 5,agility: 5,fortune: -5,shield: 5,type: 'boots',massDamage: 30,rare: 'rare'},
	{id: 193,name: 'Сабатоны пламени',damage: 10,agility: 5,fortune: -5,shield: 5,type: 'boots',massDamage: 10,rare: 'rare'},
	{id: 194,name: 'Сабатоны быстроты',agility: 10,shield: 5,type: 'boots',rare: 'basic'},
	{id: 195,name: 'Сабатоны ловкости',agility: 15,shield: 5,type: 'boots',rare: 'basic'},
	{id: 196,name: 'Сабатоны тени',damage: 15,agility: -5,fortune: -10,shield: 25,type: 'boots',rare: 'rare'},
	{id: 197,name: 'Сабатоны демона',damage: 10,agility: 10,fortune: -30,shield: -5,type: 'boots',massDamage: 10,rare: 'epic'},
	{id: 198,name: 'Сабатоны невидимости',agility: 20,shield: 20,type: 'boots',rare: 'epic'},
	{id: 199,name: 'Сабатоны удачи',agility: 5,fortune: 20,shield: 5,type: 'boots',rare: 'basic'},
	{id: 200,name: 'Сабатоны яда',damage: 30,agility: 5,shield: -45,type: 'boots',rare: 'epic'},
	{id: 201,name: 'Сабатоны героя',damage: 10,agility: 15,fortune: 10,shield: 15,type: 'boots',massDamage: 10,rare: 'epic'},
	{id: 202,name: 'Сабатоны мудрости',damage: -10,agility: 5,fortune: 20,shield: 5,type: 'boots',rare: 'rare'},
	{id: 203,name: 'Сабатоны Короля',damage: 10,agility: 5,fortune: 10,type: 'boots',massDamage: 10,rare: 'epic'},
	{id: 204,name: 'Сабатоны силы',damage: 20,agility: 15,fortune: -5,type: 'boots',rare: 'epic'},
	{id: 205,name: 'Сабатоны берсерка',damage: 20,agility: -45,shield: -15,type: 'boots',massDamage: 10,rare: 'epic'},
	{id: 206,name: 'Сабатоны древних',damage: -20,agility: 25,fortune: 20,shield: 25,type: 'boots',massDamage: 20,rare: 'epic'},
	{id: 207,name: 'Сабатоны ',agility: 5,shield: 5,type: 'boots',rare: 'basic'},
	{id: 208,name: 'Ряса бури',damage: 5,shield: 5,type: 'chest',massDamage: 30,rare: 'rare'},
	{id: 209,name: 'Ряса пламени',damage: 10,shield: 5,type: 'chest',massDamage: 10,rare: 'rare'},
	{id: 210,name: 'Ряса быстроты',agility: 5,fortune: 5,shield: 5,type: 'chest',rare: 'basic'},
	{id: 211,name: 'Ряса ловкости',agility: 10,fortune: 5,shield: 5,type: 'chest',rare: 'basic'},
	{id: 212,name: 'Ряса тени',damage: 15,agility: -10,fortune: -5,shield: 25,type: 'chest',rare: 'rare'},
	{id: 213,name: 'Ряса демона',damage: 10,agility: 5,fortune: -25,shield: -5,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 214,name: 'Ряса невидимости',agility: 15,fortune: 5,shield: 20,type: 'chest',rare: 'epic'},
	{id: 215,name: 'Ряса удачи',fortune: 25,shield: 5,type: 'chest',rare: 'basic'},
	{id: 216,name: 'Ряса яда',damage: 30,fortune: 5,shield: -45,type: 'chest',rare: 'epic'},
	{id: 217,name: 'Ряса героя',damage: 10,agility: 10,fortune: 15,shield: 15,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 218,name: 'Ряса мудрости',damage: -10,fortune: 25,shield: 5,type: 'chest',rare: 'rare'},
	{id: 219,name: 'Ряса Короля',damage: 10,fortune: 15,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 220,name: 'Ряса силы',damage: 20,agility: 10,type: 'chest',rare: 'epic'},
	{id: 221,name: 'Ряса берсерка',damage: 20,agility: -50,fortune: 5,shield: -15,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 222,name: 'Ряса древних',damage: -20,agility: 20,fortune: 25,shield: 25,type: 'chest',massDamage: 20,rare: 'epic'},
	{id: 223,name: 'Ряса ',fortune: 5,shield: 5,type: 'chest',rare: 'basic'},
	{id: 224,name: 'Мантия бури',damage: 5,agility: 10,fortune: 5,shield: -10,type: 'chest',massDamage: 30,rare: 'epic'},
	{id: 225,name: 'Мантия пламени',damage: 10,agility: 10,fortune: 5,shield: -10,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 226,name: 'Мантия быстроты',agility: 15,fortune: 10,shield: -10,type: 'chest',rare: 'rare'},
	{id: 227,name: 'Мантия ловкости',agility: 20,fortune: 10,shield: -10,type: 'chest',rare: 'rare'},
	{id: 228,name: 'Мантия тени',damage: 15,shield: 10,type: 'chest',rare: 'epic'},
	{id: 229,name: 'Мантия демона',damage: 10,agility: 15,fortune: -20,shield: -20,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 230,name: 'Мантия невидимости',agility: 25,fortune: 10,shield: 5,type: 'chest',rare: 'legendary'},
	{id: 231,name: 'Мантия удачи',agility: 10,fortune: 30,shield: -10,type: 'chest',rare: 'rare'},
	{id: 232,name: 'Мантия яда',damage: 30,agility: 10,fortune: 10,shield: -60,type: 'chest',rare: 'legendary'},
	{id: 233,name: 'Мантия героя',damage: 10,agility: 20,fortune: 20,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 234,name: 'Мантия мудрости',damage: -10,agility: 10,fortune: 30,shield: -10,type: 'chest',rare: 'epic'},
	{id: 235,name: 'Мантия Короля',damage: 10,agility: 10,fortune: 20,shield: -15,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 236,name: 'Мантия силы',damage: 20,agility: 20,fortune: 5,shield: -15,type: 'chest',rare: 'legendary'},
	{id: 237,name: 'Мантия берсерка',damage: 20,agility: -40,fortune: 10,shield: -30,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 238,name: 'Мантия древних',damage: -20,agility: 30,fortune: 30,shield: 10,type: 'chest',massDamage: 20,rare: 'legendary'},
	{id: 239,name: 'Мантия ',agility: 10,fortune: 10,shield: -10,type: 'chest',rare: 'rare'},
	{id: 240,name: 'Катализатор бури',damage: 15,fortune: 5,type: 'chest',massDamage: 50,rare: 'epic'},
	{id: 241,name: 'Катализатор пламени',damage: 20,fortune: 5,type: 'chest',massDamage: 30,rare: 'epic'},
	{id: 242,name: 'Катализатор быстроты',damage: 10,agility: 5,fortune: 10,type: 'chest',massDamage: 20,rare: 'rare'},
	{id: 243,name: 'Катализатор ловкости',damage: 10,agility: 10,fortune: 10,type: 'chest',massDamage: 20,rare: 'rare'},
	{id: 244,name: 'Катализатор тени',damage: 25,agility: -10,shield: 20,type: 'chest',massDamage: 20,rare: 'epic'},
	{id: 245,name: 'Катализатор демона',damage: 20,agility: 5,fortune: -20,shield: -10,type: 'chest',massDamage: 30,rare: 'legendary'},
	{id: 246,name: 'Катализатор невидимости',damage: 10,agility: 15,fortune: 10,shield: 15,type: 'chest',massDamage: 20,rare: 'legendary'},
	{id: 247,name: 'Катализатор удачи',damage: 10,fortune: 30,type: 'chest',massDamage: 20,rare: 'rare'},
	{id: 248,name: 'Катализатор яда',damage: 40,fortune: 10,shield: -50,type: 'chest',massDamage: 20,rare: 'legendary'},
	{id: 249,name: 'Катализатор героя',damage: 20,agility: 10,fortune: 20,shield: 10,type: 'chest',massDamage: 30,rare: 'legendary'},
	{id: 250,name: 'Катализатор мудрости',fortune: 30,type: 'chest',massDamage: 20,rare: 'epic'},
	{id: 251,name: 'Катализатор Короля',damage: 20,fortune: 20,shield: -5,type: 'chest',massDamage: 30,rare: 'legendary'},
	{id: 252,name: 'Катализатор силы',damage: 30,agility: 10,fortune: 5,shield: -5,type: 'chest',massDamage: 20,rare: 'legendary'},
	{id: 253,name: 'Катализатор берсерка',damage: 30,agility: -50,fortune: 10,shield: -20,type: 'chest',massDamage: 30,rare: 'legendary'},
	{id: 254,name: 'Катализатор древних',damage: -10,agility: 20,fortune: 30,shield: 20,type: 'chest',massDamage: 40,rare: 'legendary'},
	{id: 255,name: 'Катализатор ',damage: 10,fortune: 10,type: 'chest',massDamage: 20,rare: 'rare'},
	{id: 256,name: 'Корона бури',damage: 5,fortune: -5,shield: 5,type: 'hat',massDamage: 30,rare: 'rare'},
	{id: 257,name: 'Корона пламени',damage: 10,fortune: -5,shield: 5,type: 'hat',massDamage: 10,rare: 'rare'},
	{id: 258,name: 'Корона быстроты',agility: 5,shield: 5,type: 'hat',rare: 'basic'},
	{id: 259,name: 'Корона ловкости',agility: 10,shield: 5,type: 'hat',rare: 'basic'},
	{id: 260,name: 'Корона тени',damage: 15,agility: -10,fortune: -10,shield: 25,type: 'hat',rare: 'rare'},
	{id: 261,name: 'Корона демона',damage: 10,agility: 5,fortune: -30,shield: -5,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 262,name: 'Корона невидимости',agility: 15,shield: 20,type: 'hat',rare: 'epic'},
	{id: 263,name: 'Корона удачи',fortune: 20,shield: 5,type: 'hat',rare: 'basic'},
	{id: 264,name: 'Корона яда',damage: 30,shield: -45,type: 'hat',rare: 'epic'},
	{id: 265,name: 'Корона героя',damage: 10,agility: 10,fortune: 10,shield: 15,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 266,name: 'Корона мудрости',damage: -10,fortune: 20,shield: 5,type: 'hat',rare: 'rare'},
	{id: 267,name: 'Корона Короля',damage: 10,fortune: 10,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 268,name: 'Корона силы',damage: 20,agility: 10,fortune: -5,type: 'hat',rare: 'epic'},
	{id: 269,name: 'Корона берсерка',damage: 20,agility: -50,shield: -15,type: 'hat',massDamage: 10,rare: 'epic'},
	{id: 270,name: 'Корона древних',damage: -20,agility: 20,fortune: 20,shield: 25,type: 'hat',massDamage: 20,rare: 'epic'},
	{id: 271,name: 'Корона ',shield: 5,type: 'hat',rare: 'basic'},
	{id: 272,name: 'Магия бури',damage: 5,fortune: -5,type: 'weapon',massDamage: 40,rare: 'epic'},
	{id: 273,name: 'Магия пламени',damage: 10,fortune: -5,type: 'weapon',massDamage: 20,rare: 'epic'},
	{id: 274,name: 'Магия быстроты',agility: 5,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 275,name: 'Магия ловкости',agility: 10,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 276,name: 'Магия тени',damage: 15,agility: -10,fortune: -10,shield: 20,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 277,name: 'Магия демона',damage: 10,agility: 5,fortune: -30,shield: -10,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 278,name: 'Магия невидимости',agility: 15,shield: 15,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 279,name: 'Магия удачи',fortune: 20,type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 280,name: 'Магия яда',damage: 30,shield: -50,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 281,name: 'Магия героя',damage: 10,agility: 10,fortune: 10,shield: 10,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 282,name: 'Магия мудрости',damage: -10,fortune: 20,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 283,name: 'Магия Короля',damage: 10,fortune: 10,shield: -5,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 284,name: 'Магия силы',damage: 20,agility: 10,fortune: -5,shield: -5,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 285,name: 'Магия берсерка',damage: 20,agility: -50,shield: -20,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 286,name: 'Магия древних',damage: -20,agility: 20,fortune: 20,shield: 20,type: 'weapon',massDamage: 30,rare: 'legendary'},
	{id: 287,name: 'Магия ',type: 'weapon',massDamage: 10,rare: 'rare'},
	{id: 288,name: 'Плащ бури',damage: 5,fortune: -5,type: 'chest',massDamage: 30,rare: 'epic'},
	{id: 289,name: 'Плащ пламени',damage: 10,fortune: -5,type: 'chest',massDamage: 10,rare: 'epic'},
	{id: 290,name: 'Плащ быстроты',agility: 5,type: 'chest',rare: 'rare'},
	{id: 291,name: 'Плащ ловкости',agility: 10,type: 'chest',rare: 'rare'},
	{id: 292,name: 'Плащ тени',damage: 15,agility: -10,fortune: -10,shield: 20,type: 'chest',rare: 'epic'},
	{id: 293,name: 'Плащ демона',damage: 10,agility: 5,fortune: -30,shield: -10,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 294,name: 'Плащ невидимости',agility: 15,shield: 15,type: 'chest',rare: 'legendary'},
	{id: 295,name: 'Плащ удачи',fortune: 20,type: 'chest',rare: 'rare'},
	{id: 296,name: 'Плащ яда',damage: 30,shield: -50,type: 'chest',rare: 'legendary'},
	{id: 297,name: 'Плащ героя',damage: 10,agility: 10,fortune: 10,shield: 10,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 298,name: 'Плащ мудрости',damage: -10,fortune: 20,type: 'chest',rare: 'epic'},
	{id: 299,name: 'Плащ Короля',damage: 10,fortune: 10,shield: -5,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 300,name: 'Плащ силы',damage: 20,agility: 10,fortune: -5,shield: -5,type: 'chest',rare: 'legendary'},
	{id: 301,name: 'Плащ берсерка',damage: 20,agility: -50,shield: -20,type: 'chest',massDamage: 10,rare: 'legendary'},
	{id: 302,name: 'Плащ древних',damage: -20,agility: 20,fortune: 20,shield: 20,type: 'chest',massDamage: 20,rare: 'legendary'},
	{id: 303,name: 'Плащ ',type: 'chest',rare: 'rare'},
	{id: 304,name: 'Артефакт бури',damage: 5,fortune: -5,type: 'weapon',massDamage: 30,rare: 'epic'},
	{id: 305,name: 'Артефакт пламени',damage: 10,fortune: -5,type: 'weapon',massDamage: 10,rare: 'epic'},
	{id: 306,name: 'Артефакт быстроты',agility: 5,type: 'weapon',rare: 'rare'},
	{id: 307,name: 'Артефакт ловкости',agility: 10,type: 'weapon',rare: 'rare'},
	{id: 308,name: 'Артефакт тени',damage: 15,agility: -10,fortune: -10,shield: 20,type: 'weapon',rare: 'epic'},
	{id: 309,name: 'Артефакт демона',damage: 10,agility: 5,fortune: -30,shield: -10,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 310,name: 'Артефакт невидимости',agility: 15,shield: 15,type: 'weapon',rare: 'legendary'},
	{id: 311,name: 'Артефакт удачи',fortune: 20,type: 'weapon',rare: 'rare'},
	{id: 312,name: 'Артефакт яда',damage: 30,shield: -50,type: 'weapon',rare: 'legendary'},
	{id: 313,name: 'Артефакт героя',damage: 10,agility: 10,fortune: 10,shield: 10,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 314,name: 'Артефакт мудрости',damage: -10,fortune: 20,type: 'weapon',rare: 'epic'},
	{id: 315,name: 'Артефакт Короля',damage: 10,fortune: 10,shield: -5,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 316,name: 'Артефакт силы',damage: 20,agility: 10,fortune: -5,shield: -5,type: 'weapon',rare: 'legendary'},
	{id: 317,name: 'Артефакт берсерка',damage: 20,agility: -50,shield: -20,type: 'weapon',massDamage: 10,rare: 'legendary'},
	{id: 318,name: 'Артефакт древних',damage: -20,agility: 20,fortune: 20,shield: 20,type: 'weapon',massDamage: 20,rare: 'legendary'},
	{id: 319,name: 'Артефакт ',type: 'weapon',rare: 'rare'},
	{id: 320,name: 'Реликвия бури',damage: 5,fortune: -5,type: 'special',massDamage: 30,rare: 'epic'},
	{id: 321,name: 'Реликвия пламени',damage: 10,fortune: -5,type: 'special',massDamage: 10,rare: 'epic'},
	{id: 322,name: 'Реликвия быстроты',agility: 5,type: 'special',rare: 'rare'},
	{id: 323,name: 'Реликвия ловкости',agility: 10,type: 'special',rare: 'rare'},
	{id: 324,name: 'Реликвия тени',damage: 15,agility: -10,fortune: -10,shield: 20,type: 'special',rare: 'epic'},
	{id: 325,name: 'Реликвия демона',damage: 10,agility: 5,fortune: -30,shield: -10,type: 'special',massDamage: 10,rare: 'legendary'},
	{id: 326,name: 'Реликвия невидимости',agility: 15,shield: 15,type: 'special',rare: 'legendary'},
	{id: 327,name: 'Реликвия удачи',fortune: 20,type: 'special',rare: 'rare'},
	{id: 328,name: 'Реликвия яда',damage: 30,shield: -50,type: 'special',rare: 'legendary'},
	{id: 329,name: 'Реликвия героя',damage: 10,agility: 10,fortune: 10,shield: 10,type: 'special',massDamage: 10,rare: 'legendary'},
	{id: 330,name: 'Реликвия мудрости',damage: -10,fortune: 20,type: 'special',rare: 'epic'},
	{id: 331,name: 'Реликвия Короля',damage: 10,fortune: 10,shield: -5,type: 'special',massDamage: 10,rare: 'legendary'},
	{id: 332,name: 'Реликвия силы',damage: 20,agility: 10,fortune: -5,shield: -5,type: 'special',rare: 'legendary'},
	{id: 333,name: 'Реликвия берсерка',damage: 20,agility: -50,shield: -20,type: 'special',massDamage: 10,rare: 'legendary'},
	{id: 334,name: 'Реликвия древних',damage: -20,agility: 20,fortune: 20,shield: 20,type: 'special',massDamage: 20,rare: 'legendary'},
	{id: 335,name: 'Реликвия ',type: 'special',rare: 'rare'},
	
	]