import { ItemType } from '../types/types'

export const items: ItemType[] = [
	{ id: 0, name: 'Меч бури', damage: 10, fortune: -5, type: 'weapon' },
	{ id: 1, name: 'Меч пламени', damage: 15, fortune: -5, type: 'weapon' },
	{ id: 2, name: 'Меч быстроты', damage: 5, agility: 5, type: 'weapon' },
	{ id: 3, name: 'Меч ловкости', damage: 5, agility: 10, type: 'weapon' },
	{
		id: 4,
		name: 'Меч тени',
		damage: 20,
		agility: -10,
		fortune: -10,
		shield: 20,
		type: 'weapon',
	},
	{
		id: 5,
		name: 'Меч демона',
		damage: 15,
		agility: 5,
		fortune: -30,
		shield: -10,
		type: 'weapon',
	},
	{
		id: 6,
		name: 'Меч невидимости',
		damage: 5,
		agility: 15,
		shield: 15,
		type: 'weapon',
	},
	{ id: 7, name: 'Меч удачи', damage: 5, fortune: 20, type: 'weapon' },
	{ id: 8, name: 'Меч яда', damage: 35, shield: -50, type: 'weapon' },
	{
		id: 9,
		name: 'Меч героя',
		damage: 15,
		agility: 10,
		fortune: 10,
		shield: 10,
		type: 'weapon',
	},
	{ id: 10, name: 'Меч мудрости', damage: -5, fortune: 20, type: 'weapon' },
	{ id: 11, name: 'Секира бури', damage: 10, fortune: -5, type: 'weapon' },
	{ id: 12, name: 'Секира пламени', damage: 15, fortune: -5, type: 'weapon' },
	{ id: 13, name: 'Секира быстроты', damage: 5, agility: 5, type: 'weapon' },
	{ id: 14, name: 'Секира ловкости', damage: 5, agility: 10, type: 'weapon' },
	{
		id: 15,
		name: 'Секира тени',
		damage: 20,
		agility: -10,
		fortune: -10,
		shield: 20,
		type: 'weapon',
	},
	{
		id: 16,
		name: 'Секира демона',
		damage: 15,
		agility: 5,
		fortune: -30,
		shield: -10,
		type: 'weapon',
	},
	{
		id: 17,
		name: 'Секира невидимости',
		damage: 5,
		agility: 15,
		shield: 15,
		type: 'weapon',
	},
	{ id: 18, name: 'Секира удачи', damage: 5, fortune: 20, type: 'weapon' },
	{ id: 19, name: 'Секира яда', damage: 35, shield: -50, type: 'weapon' },
	{
		id: 20,
		name: 'Секира героя',
		damage: 15,
		agility: 10,
		fortune: 10,
		shield: 10,
		type: 'weapon',
	},
	{ id: 21, name: 'Секира мудрости', damage: -5, fortune: 20, type: 'weapon' },
	{ id: 22, name: 'Топоры бури', damage: 15, fortune: -5, type: 'weapon' },
	{ id: 23, name: 'Топоры пламени', damage: 20, fortune: -5, type: 'weapon' },
	{ id: 24, name: 'Топоры быстроты', damage: 10, agility: 5, type: 'weapon' },
	{ id: 25, name: 'Топоры ловкости', damage: 10, agility: 10, type: 'weapon' },
	{
		id: 26,
		name: 'Топоры тени',
		damage: 25,
		agility: -10,
		fortune: -10,
		shield: 20,
		type: 'weapon',
	},
	{
		id: 27,
		name: 'Топоры демона',
		damage: 20,
		agility: 5,
		fortune: -30,
		shield: -10,
		type: 'weapon',
	},
	{
		id: 28,
		name: 'Топоры невидимости',
		damage: 10,
		agility: 15,
		shield: 15,
		type: 'weapon',
	},
	{ id: 29, name: 'Топоры удачи', damage: 10, fortune: 20, type: 'weapon' },
	{ id: 30, name: 'Топоры яда', damage: 40, shield: -50, type: 'weapon' },
	{
		id: 31,
		name: 'Топоры героя',
		damage: 20,
		agility: 10,
		fortune: 10,
		shield: 10,
		type: 'weapon',
	},
	{ id: 32, name: 'Топоры мудрости', fortune: 20, type: 'weapon' },
	{ id: 33, name: 'Посох бури', damage: 10, fortune: 5, type: 'weapon' },
	{ id: 34, name: 'Посох пламени', damage: 15, fortune: 5, type: 'weapon' },
	{
		id: 35,
		name: 'Посох быстроты',
		damage: 5,
		agility: 5,
		fortune: 10,
		type: 'weapon',
	},
	{
		id: 36,
		name: 'Посох ловкости',
		damage: 5,
		agility: 10,
		fortune: 10,
		type: 'weapon',
	},
	{
		id: 37,
		name: 'Посох тени',
		damage: 20,
		agility: -10,
		shield: 20,
		type: 'weapon',
	},
	{
		id: 38,
		name: 'Посох демона',
		damage: 15,
		agility: 5,
		fortune: -20,
		shield: -10,
		type: 'weapon',
	},
	{
		id: 39,
		name: 'Посох невидимости',
		damage: 5,
		agility: 15,
		fortune: 10,
		shield: 15,
		type: 'weapon',
	},
	{ id: 40, name: 'Посох удачи', damage: 5, fortune: 30, type: 'weapon' },
	{
		id: 41,
		name: 'Посох яда',
		damage: 35,
		fortune: 10,
		shield: -50,
		type: 'weapon',
	},
	{
		id: 42,
		name: 'Посох героя',
		damage: 15,
		agility: 10,
		fortune: 20,
		shield: 10,
		type: 'weapon',
	},
	{ id: 43, name: 'Посох мудрости', damage: -5, fortune: 30, type: 'weapon' },
	{
		id: 44,
		name: 'Щит бури',
		damage: 5,
		fortune: -5,
		shield: 10,
		type: 'shield',
	},
	{
		id: 45,
		name: 'Щит пламени',
		damage: 10,
		fortune: -5,
		shield: 10,
		type: 'shield',
	},
	{ id: 46, name: 'Щит быстроты', agility: 5, shield: 10, type: 'shield' },
	{ id: 47, name: 'Щит ловкости', agility: 10, shield: 10, type: 'shield' },
	{
		id: 48,
		name: 'Щит тени',
		damage: 15,
		agility: -10,
		fortune: -10,
		shield: 30,
		type: 'shield',
	},
	{
		id: 49,
		name: 'Щит демона',
		damage: 10,
		agility: 5,
		fortune: -30,
		type: 'shield',
	},
	{ id: 50, name: 'Щит невидимости', agility: 15, shield: 25, type: 'shield' },
	{ id: 51, name: 'Щит удачи', fortune: 20, shield: 10, type: 'shield' },
	{ id: 52, name: 'Щит яда', damage: 30, shield: -40, type: 'shield' },
	{
		id: 53,
		name: 'Щит героя',
		damage: 10,
		agility: 10,
		fortune: 10,
		shield: 20,
		type: 'shield',
	},
	{
		id: 54,
		name: 'Щит мудрости',
		damage: -10,
		fortune: 20,
		shield: 10,
		type: 'shield',
	},
	{
		id: 55,
		name: 'Баррикада бури',
		damage: 5,
		fortune: -5,
		shield: 20,
		type: 'shield',
	},
	{
		id: 56,
		name: 'Баррикада пламени',
		damage: 10,
		fortune: -5,
		shield: 20,
		type: 'shield',
	},
	{
		id: 57,
		name: 'Баррикада быстроты',
		agility: 5,
		shield: 20,
		type: 'shield',
	},
	{
		id: 58,
		name: 'Баррикада ловкости',
		agility: 10,
		shield: 20,
		type: 'shield',
	},
	{
		id: 59,
		name: 'Баррикада тени',
		damage: 15,
		agility: -10,
		fortune: -10,
		shield: 40,
		type: 'shield',
	},
	{
		id: 60,
		name: 'Баррикада демона',
		damage: 10,
		agility: 5,
		fortune: -30,
		shield: 10,
		type: 'shield',
	},
	{
		id: 61,
		name: 'Баррикада невидимости',
		agility: 15,
		shield: 35,
		type: 'shield',
	},
	{ id: 62, name: 'Баррикада удачи', fortune: 20, shield: 20, type: 'shield' },
	{ id: 63, name: 'Баррикада яда', damage: 30, shield: -30, type: 'shield' },
	{
		id: 64,
		name: 'Баррикада героя',
		damage: 10,
		agility: 10,
		fortune: 10,
		shield: 30,
		type: 'shield',
	},
	{
		id: 65,
		name: 'Баррикада мудрости',
		damage: -10,
		fortune: 20,
		shield: 20,
		type: 'shield',
	},
	{
		id: 66,
		name: 'Лук бури',
		damage: 10,
		agility: 10,
		fortune: -5,
		type: 'weapon',
	},
	{
		id: 67,
		name: 'Лук пламени',
		damage: 15,
		agility: 10,
		fortune: -5,
		type: 'weapon',
	},
	{ id: 68, name: 'Лук быстроты', damage: 5, agility: 15, type: 'weapon' },
	{ id: 69, name: 'Лук ловкости', damage: 5, agility: 20, type: 'weapon' },
	{
		id: 70,
		name: 'Лук тени',
		damage: 20,
		fortune: -10,
		shield: 20,
		type: 'weapon',
	},
	{
		id: 71,
		name: 'Лук демона',
		damage: 15,
		agility: 15,
		fortune: -30,
		shield: -10,
		type: 'weapon',
	},
	{
		id: 72,
		name: 'Лук невидимости',
		damage: 5,
		agility: 25,
		shield: 15,
		type: 'weapon',
	},
	{
		id: 73,
		name: 'Лук удачи',
		damage: 5,
		agility: 10,
		fortune: 20,
		type: 'weapon',
	},
	{
		id: 74,
		name: 'Лук яда',
		damage: 35,
		agility: 10,
		shield: -50,
		type: 'weapon',
	},
	{
		id: 75,
		name: 'Лук героя',
		damage: 15,
		agility: 20,
		fortune: 10,
		shield: 10,
		type: 'weapon',
	},
	{
		id: 76,
		name: 'Лук мудрости',
		damage: -5,
		agility: 10,
		fortune: 20,
		type: 'weapon',
	},
	{
		id: 77,
		name: 'Двуручный меч бури',
		damage: 15,
		fortune: -5,
		shield: 5,
		type: 'weapon',
	},
	{
		id: 78,
		name: 'Двуручный меч пламени',
		damage: 20,
		fortune: -5,
		shield: 5,
		type: 'weapon',
	},
	{
		id: 79,
		name: 'Двуручный меч быстроты',
		damage: 10,
		agility: 5,
		shield: 5,
		type: 'weapon',
	},
	{
		id: 80,
		name: 'Двуручный меч ловкости',
		damage: 10,
		agility: 10,
		shield: 5,
		type: 'weapon',
	},
	{
		id: 81,
		name: 'Двуручный меч тени',
		damage: 25,
		agility: -10,
		fortune: -10,
		shield: 25,
		type: 'weapon',
	},
	{
		id: 82,
		name: 'Двуручный меч демона',
		damage: 20,
		agility: 5,
		fortune: -30,
		shield: -5,
		type: 'weapon',
	},
	{
		id: 83,
		name: 'Двуручный меч невидимости',
		damage: 10,
		agility: 15,
		shield: 20,
		type: 'weapon',
	},
	{
		id: 84,
		name: 'Двуручный меч удачи',
		damage: 10,
		fortune: 20,
		shield: 5,
		type: 'weapon',
	},
	{
		id: 85,
		name: 'Двуручный меч яда',
		damage: 40,
		shield: -45,
		type: 'weapon',
	},
	{
		id: 86,
		name: 'Двуручный меч героя',
		damage: 20,
		agility: 10,
		fortune: 10,
		shield: 15,
		type: 'weapon',
	},
	{
		id: 87,
		name: 'Двуручный меч мудрости',
		fortune: 20,
		shield: 5,
		type: 'weapon',
	},
	{
		id: 88,
		name: 'Кираса бури',
		damage: 5,
		agility: -5,
		fortune: -5,
		shield: 10,
		type: 'chest',
	},
	{
		id: 89,
		name: 'Кираса пламени',
		damage: 10,
		agility: -5,
		fortune: -5,
		shield: 10,
		type: 'chest',
	},
	{ id: 90, name: 'Кираса быстроты', shield: 10, type: 'chest' },
	{ id: 91, name: 'Кираса ловкости', agility: 5, shield: 10, type: 'chest' },
	{
		id: 92,
		name: 'Кираса тени',
		damage: 15,
		agility: -15,
		fortune: -10,
		shield: 30,
		type: 'chest',
	},
	{ id: 93, name: 'Кираса демона', damage: 10, fortune: -30, type: 'chest' },
	{
		id: 94,
		name: 'Кираса невидимости',
		agility: 10,
		shield: 25,
		type: 'chest',
	},
	{
		id: 95,
		name: 'Кираса удачи',
		agility: -5,
		fortune: 20,
		shield: 10,
		type: 'chest',
	},
	{
		id: 96,
		name: 'Кираса яда',
		damage: 30,
		agility: -5,
		shield: -40,
		type: 'chest',
	},
	{
		id: 97,
		name: 'Кираса героя',
		damage: 10,
		agility: 5,
		fortune: 10,
		shield: 20,
		type: 'chest',
	},
	{
		id: 98,
		name: 'Кираса мудрости',
		damage: -10,
		agility: -5,
		fortune: 20,
		shield: 10,
		type: 'chest',
	},
	{ id: 99, name: 'Шлем бури', damage: 5, fortune: -5, shield: 5, type: 'hat' },
	{
		id: 100,
		name: 'Шлем пламени',
		damage: 10,
		fortune: -5,
		shield: 5,
		type: 'hat',
	},
	{ id: 101, name: 'Шлем быстроты', agility: 5, shield: 5, type: 'hat' },
	{ id: 102, name: 'Шлем ловкости', agility: 10, shield: 5, type: 'hat' },
	{
		id: 103,
		name: 'Шлем тени',
		damage: 15,
		agility: -10,
		fortune: -10,
		shield: 25,
		type: 'hat',
	},
	{
		id: 104,
		name: 'Шлем демона',
		damage: 10,
		agility: 5,
		fortune: -30,
		shield: -5,
		type: 'hat',
	},
	{ id: 105, name: 'Шлем невидимости', agility: 15, shield: 20, type: 'hat' },
	{ id: 106, name: 'Шлем удачи', fortune: 20, shield: 5, type: 'hat' },
	{ id: 107, name: 'Шлем яда', damage: 30, shield: -45, type: 'hat' },
	{
		id: 108,
		name: 'Шлем героя',
		damage: 10,
		agility: 10,
		fortune: 10,
		shield: 15,
		type: 'hat',
	},
	{
		id: 109,
		name: 'Шлем мудрости',
		damage: -10,
		fortune: 20,
		shield: 5,
		type: 'hat',
	},
	{ id: 110, name: 'Шляпа бури', damage: 5, fortune: 5, type: 'hat' },
	{ id: 111, name: 'Шляпа пламени', damage: 10, fortune: 5, type: 'hat' },
	{ id: 112, name: 'Шляпа быстроты', agility: 5, fortune: 10, type: 'hat' },
	{ id: 113, name: 'Шляпа ловкости', agility: 10, fortune: 10, type: 'hat' },
	{
		id: 114,
		name: 'Шляпа тени',
		damage: 15,
		agility: -10,
		shield: 20,
		type: 'hat',
	},
	{
		id: 115,
		name: 'Шляпа демона',
		damage: 10,
		agility: 5,
		fortune: -20,
		shield: -10,
		type: 'hat',
	},
	{
		id: 116,
		name: 'Шляпа невидимости',
		agility: 15,
		fortune: 10,
		shield: 15,
		type: 'hat',
	},
	{ id: 117, name: 'Шляпа удачи', fortune: 30, type: 'hat' },
	{
		id: 118,
		name: 'Шляпа яда',
		damage: 30,
		fortune: 10,
		shield: -50,
		type: 'hat',
	},
	{
		id: 119,
		name: 'Шляпа героя',
		damage: 10,
		agility: 10,
		fortune: 20,
		shield: 10,
		type: 'hat',
	},
	{ id: 120, name: 'Шляпа мудрости', damage: -10, fortune: 30, type: 'hat' },
	{
		id: 121,
		name: 'Поножи бури',
		damage: 5,
		fortune: -5,
		shield: 5,
		type: 'pants',
	},
	{
		id: 122,
		name: 'Поножи пламени',
		damage: 10,
		fortune: -5,
		shield: 5,
		type: 'pants',
	},
	{ id: 123, name: 'Поножи быстроты', agility: 5, shield: 5, type: 'pants' },
	{ id: 124, name: 'Поножи ловкости', agility: 10, shield: 5, type: 'pants' },
	{
		id: 125,
		name: 'Поножи тени',
		damage: 15,
		agility: -10,
		fortune: -10,
		shield: 25,
		type: 'pants',
	},
	{
		id: 126,
		name: 'Поножи демона',
		damage: 10,
		agility: 5,
		fortune: -30,
		shield: -5,
		type: 'pants',
	},
	{
		id: 127,
		name: 'Поножи невидимости',
		agility: 15,
		shield: 20,
		type: 'pants',
	},
	{ id: 128, name: 'Поножи удачи', fortune: 20, shield: 5, type: 'pants' },
	{ id: 129, name: 'Поножи яда', damage: 30, shield: -45, type: 'pants' },
	{
		id: 130,
		name: 'Поножи героя',
		damage: 10,
		agility: 10,
		fortune: 10,
		shield: 15,
		type: 'pants',
	},
	{
		id: 131,
		name: 'Поножи мудрости',
		damage: -10,
		fortune: 20,
		shield: 5,
		type: 'pants',
	},
	{
		id: 132,
		name: 'Сабатоны бури',
		damage: 5,
		agility: 5,
		fortune: -5,
		shield: 5,
		type: 'boots',
	},
	{
		id: 133,
		name: 'Сабатоны пламени',
		damage: 10,
		agility: 5,
		fortune: -5,
		shield: 5,
		type: 'boots',
	},
	{ id: 134, name: 'Сабатоны быстроты', agility: 10, shield: 5, type: 'boots' },
	{ id: 135, name: 'Сабатоны ловкости', agility: 15, shield: 5, type: 'boots' },
	{
		id: 136,
		name: 'Сабатоны тени',
		damage: 15,
		agility: -5,
		fortune: -10,
		shield: 25,
		type: 'boots',
	},
	{
		id: 137,
		name: 'Сабатоны демона',
		damage: 10,
		agility: 10,
		fortune: -30,
		shield: -5,
		type: 'boots',
	},
	{
		id: 138,
		name: 'Сабатоны невидимости',
		agility: 20,
		shield: 20,
		type: 'boots',
	},
	{
		id: 139,
		name: 'Сабатоны удачи',
		agility: 5,
		fortune: 20,
		shield: 5,
		type: 'boots',
	},
	{
		id: 140,
		name: 'Сабатоны яда',
		damage: 30,
		agility: 5,
		shield: -45,
		type: 'boots',
	},
	{
		id: 141,
		name: 'Сабатоны героя',
		damage: 10,
		agility: 15,
		fortune: 10,
		shield: 15,
		type: 'boots',
	},
	{
		id: 142,
		name: 'Сабатоны мудрости',
		damage: -10,
		agility: 5,
		fortune: 20,
		shield: 5,
		type: 'boots',
	},
	{ id: 143, name: 'Ряса бури', damage: 5, shield: 5, type: 'chest' },
	{ id: 144, name: 'Ряса пламени', damage: 10, shield: 5, type: 'chest' },
	{
		id: 145,
		name: 'Ряса быстроты',
		agility: 5,
		fortune: 5,
		shield: 5,
		type: 'chest',
	},
	{
		id: 146,
		name: 'Ряса ловкости',
		agility: 10,
		fortune: 5,
		shield: 5,
		type: 'chest',
	},
	{
		id: 147,
		name: 'Ряса тени',
		damage: 15,
		agility: -10,
		fortune: -5,
		shield: 25,
		type: 'chest',
	},
	{
		id: 148,
		name: 'Ряса демона',
		damage: 10,
		agility: 5,
		fortune: -25,
		shield: -5,
		type: 'chest',
	},
	{
		id: 149,
		name: 'Ряса невидимости',
		agility: 15,
		fortune: 5,
		shield: 20,
		type: 'chest',
	},
	{ id: 150, name: 'Ряса удачи', fortune: 25, shield: 5, type: 'chest' },
	{
		id: 151,
		name: 'Ряса яда',
		damage: 30,
		fortune: 5,
		shield: -45,
		type: 'chest',
	},
	{
		id: 152,
		name: 'Ряса героя',
		damage: 10,
		agility: 10,
		fortune: 15,
		shield: 15,
		type: 'chest',
	},
	{
		id: 153,
		name: 'Ряса мудрости',
		damage: -10,
		fortune: 25,
		shield: 5,
		type: 'chest',
	},
	{
		id: 154,
		name: 'Мантия бури',
		damage: 5,
		agility: 10,
		fortune: 5,
		shield: -10,
		type: 'chest',
	},
	{
		id: 155,
		name: 'Мантия пламени',
		damage: 10,
		agility: 10,
		fortune: 5,
		shield: -10,
		type: 'chest',
	},
	{
		id: 156,
		name: 'Мантия быстроты',
		agility: 15,
		fortune: 10,
		shield: -10,
		type: 'chest',
	},
	{
		id: 157,
		name: 'Мантия ловкости',
		agility: 20,
		fortune: 10,
		shield: -10,
		type: 'chest',
	},
	{ id: 158, name: 'Мантия тени', damage: 15, shield: 10, type: 'chest' },
	{
		id: 159,
		name: 'Мантия демона',
		damage: 10,
		agility: 15,
		fortune: -20,
		shield: -20,
		type: 'chest',
	},
	{
		id: 160,
		name: 'Мантия невидимости',
		agility: 25,
		fortune: 10,
		shield: 5,
		type: 'chest',
	},
	{
		id: 161,
		name: 'Мантия удачи',
		agility: 10,
		fortune: 30,
		shield: -10,
		type: 'chest',
	},
	{
		id: 162,
		name: 'Мантия яда',
		damage: 30,
		agility: 10,
		fortune: 10,
		shield: -60,
		type: 'chest',
	},
	{
		id: 163,
		name: 'Мантия героя',
		damage: 10,
		agility: 20,
		fortune: 20,
		type: 'chest',
	},
	{
		id: 164,
		name: 'Мантия мудрости',
		damage: -10,
		agility: 10,
		fortune: 30,
		shield: -10,
		type: 'chest',
	},
	{ id: 165, name: 'Катализатор бури', damage: 15, fortune: 5, type: 'chest' },
	{
		id: 166,
		name: 'Катализатор пламени',
		damage: 20,
		fortune: 5,
		type: 'chest',
	},
	{
		id: 167,
		name: 'Катализатор быстроты',
		damage: 10,
		agility: 5,
		fortune: 10,
		type: 'chest',
	},
	{
		id: 168,
		name: 'Катализатор ловкости',
		damage: 10,
		agility: 10,
		fortune: 10,
		type: 'chest',
	},
	{
		id: 169,
		name: 'Катализатор тени',
		damage: 25,
		agility: -10,
		shield: 20,
		type: 'chest',
	},
	{
		id: 170,
		name: 'Катализатор демона',
		damage: 20,
		agility: 5,
		fortune: -20,
		shield: -10,
		type: 'chest',
	},
	{
		id: 171,
		name: 'Катализатор невидимости',
		damage: 10,
		agility: 15,
		fortune: 10,
		shield: 15,
		type: 'chest',
	},
	{
		id: 172,
		name: 'Катализатор удачи',
		damage: 10,
		fortune: 30,
		type: 'chest',
	},
	{
		id: 173,
		name: 'Катализатор яда',
		damage: 40,
		fortune: 10,
		shield: -50,
		type: 'chest',
	},
	{
		id: 174,
		name: 'Катализатор героя',
		damage: 20,
		agility: 10,
		fortune: 20,
		shield: 10,
		type: 'chest',
	},
	{ id: 175, name: 'Катализатор мудрости', fortune: 30, type: 'chest' },
]
